GovAlta/adsp-monorepo

apps/tenant-management-webapp/src/app/pages/admin/dashboard/dashboard.tsx
libs/adsp-service-net-sdk/Access/AccessExtensions.Spec.cs
libs/adsp-service-net-sdk/Access/AccessExtensions.cs
libs/adsp-service-net-sdk/Access/IssuerCache.Spec.cs
libs/adsp-service-net-sdk/Access/TenantKeyProvider.Spec.cs
libs/adsp-service-net-sdk/Access/TenantKeyProvider.cs

Added unit tests to .NET Core SDK within access namespace.
The Code Coverage and Branch Coverage are listed as follows, respectively:
AccessClaimRoles:  100% N/A
AccessExtensions:   22.9% 9% - Cannot access to jwt => {} block in the AddJwtBearer.
IssuerCache: 100% 100%
MetadataResponse: 100% N/A
TenantKeyProvider: 90.9% 44.6 %- I have tested both  tenant != null and tenant == null explicitly branches for RetrieveSigningKey function. But, the branch coverage report shows the two branches have not been covered.
TokenProvider: 93.7% 88.8%

chore: update dotnet namespace access unit test

---

apps/script-service/Controllers/ScriptController.cs
apps/script-service/Events/ScriptEvent.cs
apps/script-service/Events/ScriptSubscriber.cs
apps/script-service/Services/ILuaScriptService.cs
apps/script-service/Services/LuaScriptService.cs

Also, skipping event triggering for script-service events to prevent circular executions.

feat(script-service): adding a jobId to script executions.

---

apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templates.tsx

Updating the template state within the onChange function might be unnecessary. We only need to update the state and sync with the remote when we click the save button.

fix: delete unnecessary state update

---

apps/tenant-management-webapp/src/app/lib/checkInput.ts
apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarModal.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/configuration/definitions/addEditDefinition.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/directory/directoryModal.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/events/edit.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypeModal.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/AddEditPdfTemplates.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PDFConfigForm.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templates.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/script/addScriptModal.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx

Summary of update:
Calendar service - Add calendar modal:
* Name: added word length check - 32
* Description: changed to textarea - 512
* Save button: added disabled check
Configuration service - Add definition modal:
* Namespace: truncate string - 32
* Name: truncate string - 32
* Description: changed to textarea -512
Directory service - Add entry modal:
* Service: added word length check - 32
Event service - Add definition modal:
* Name: added word length check - 32
* Namespace: added word length check - 32
File service - Add file type modal:
* Name: added word length check - 32
PDF service - Add template modal:
* Name: added word length check - 32
* Description: added word length check - 512
Template edit:
* Name: added word length check - 32
* Description: added word length check - …

Add input string length validation

---

apps/tenant-management-webapp/src/app/store/pdf/reducers.ts

... the extra data coming in at the reducer than during the saga. Occasionally the stream pumped out data for a specific file before we know about the file, and this just ignores that data. This prevents a bunch of empty fields from being displayed, thus fixing the bug

CS-1950 - Turns out its much easier to ignore

---

docs/platform/platform-dotnet-sdk.md

chore(docs): remove .NET version from github pages

---

apps/file-service/src/file/events.ts
apps/file-service/src/file/index.ts
apps/file-service/src/file/job/deleteOldFiles.ts
apps/file-service/src/file/job/index.ts
apps/file-service/src/file/job/user.ts
apps/file-service/src/file/model/file.ts
apps/file-service/src/file/types/file.ts
apps/file-service/src/file/types/type.ts
apps/file-service/src/main.ts
apps/file-service/src/mongo/file.ts

File service in the job mode runs scheduled jobs
The retention policy file deletion is a scheduled job
- runs on daily
- operation performed by the job
- - Load all tenants
- - For each tenant, load file configuration (and core file configuration)
- - For each file type with retention policy enabled, find files that should be deleted
- - Delete files
* Job handles paging files when querying
Deletion functions as regular deletion and associated domain events are emitted where ‘user’ information indicates the retention process
mark for deletion (doesn’t need to be immediately deleted from underlying storage)

CS 2038 - 

---

apps/status-service/src/app/router/serviceStatus.ts
apps/tenant-management-webapp/src/app/pages/admin/services/status/testWebhook.tsx

* Spinner is already in place to make this a smooth transition in front end
* In order to not have a delay here, I would have to add the rabbit mq service to the status service and then poll it repeatedly to see if the webhook event has been triggered. This seems overly complicated, when the delay should be minimal
* Show error if we time out
* can use https://postman-echo.com/post as test endpoint

Give the testing a more realistic delay

---

apps/task-service/src/postgres/task.ts
apps/task-service/src/task/events.ts
apps/task-service/src/task/model/task.spec.ts
apps/task-service/src/task/model/task.ts
apps/task-service/src/task/router/queue.ts

Store the assignment metadata even if the assignment is to no one.

feat(task-service): changing how task service stores un-assignment

---

apps/push-service/src/push/model/stream.spec.ts
apps/push-service/src/push/model/stream.ts

Context criteria is failed if any criteria value does not match event context, and criteria can specify a subset of values.

fix(push-service): fix event matching logic in stream entity

---

apps/task-service/src/task/events.ts
apps/task-service/src/task/router/queue.ts
apps/task-service/src/task/router/task.ts

Using the same data mapper as the router when populating the event payload so event consumers can access all properties.

feat(task-service): mapping full task into event payload

---

apps/file-service/src/file/model/file.spec.ts
apps/file-service/src/file/model/file.ts
apps/file-service/src/file/model/type.ts
apps/file-service/src/file/router/file.spec.ts

Adjusting permissions so creator is always allowed to download their own file, but users with update permission are no longer allowed to access all files of the type (i.e. files uploaded by others). General deletion is restricted to file service admin, but creators of files are allowed to delete if they still have an update role.

feat(file-service): adjusting permissions on files

---

apps/push-service/src/push/router/stream.ts
apps/status-service/src/app/jobs/checkEndpoint.spec.ts
apps/status-service/src/app/jobs/checkEndpoint.ts
apps/status-service/src/app/model/serviceStatus.ts
apps/tenant-management-webapp/src/app/pages/admin/services/status/testWebhook.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/status/webhookForm.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/status/webhookHistoryForm.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/status/webhooks/webhookDeleteModal.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/status/webhooks/webhooks.tsx
apps/tenant-management-webapp/src/app/store/event/sagas.ts
apps/tenant-management-webapp/src/app/store/status/reducers.ts
apps/tenant-management-webapp/src/app/store/status/sagas.ts

* Delete view had extra space on right / delete was not updating in backend (regression)
* webhook was only working in test and not when apps were up or down (regression)
* cleaned up test screen to not show loading when nothing is loading
* Now auto-searching when the webhook history page is openend
* re-arranged history buttons accordingly
* don't show 'no history' if we're in the middle of a reload
* Ensure the test window always has something selected

Fixes for CS-2095 / CS-2191 / CS-2146

---

apps/file-service/src/amqp/file.ts
apps/file-service/src/file/job/delete.ts
apps/file-service/src/file/job/index.ts
apps/file-service/src/file/job/scan.ts

Reducing log level of unknown job message since there are known events that are not associated with file jobs. Also increasing log level on scanning and deletion for better visibility of job success.

chore(file-service): adjusting logging of jobs

---

apps/push-service/src/main.ts
apps/push-service/src/push/index.ts
apps/push-service/src/push/router/stream.spec.ts
apps/push-service/src/push/router/stream.ts

by using a named instead of a '' queue, we should be able to prevent webhooks from being processed once for every pod

CS2192 - prevent triple processing

---

apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/pdfTemplateEditor.tsx

Should still fit in a 1920x1080 monitor's browser window

CS-2271 limit height of pdf editor as well

---

apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx

* There is a glitch in GoATextArea that causes onChange to be executed on page reload. This prevents a page reload from showing current data in the editor correct. By conditioning this refresh we can show data correctly in the editor if we happen to refresh the page inside the editor or use a link outside the app to go to a specific form editor.

Allows refresh while in editor

---

apps/comment-service/src/comment/index.ts
apps/comment-service/src/comment/model/topic.spec.ts
apps/comment-service/src/comment/model/topic.ts
apps/comment-service/src/comment/repository.ts
apps/comment-service/src/comment/router/comment.spec.ts
apps/comment-service/src/comment/router/comment.swagger.yml
apps/comment-service/src/comment/router/comment.ts
apps/comment-service/src/comment/router/index.ts
apps/comment-service/src/comment/router/topic.ts
apps/comment-service/src/comment/types/comment.ts
apps/comment-service/src/comment/types/topic.ts
apps/comment-service/src/main.ts
apps/comment-service/src/postgres/topic.ts
apps/comment-service/src/postgres/types.ts
apps/comment-service/src/utils/adspId.ts
apps/comment-service/src/utils/index.ts

Also making resourceId forgiving so it doesn't have to be an ADSP ID.

feat(comment-service): adding comments endpoint for cross topic searches

---

apps/tenant-management-webapp/src/app/lib/keycloak.ts

This should fix all the login flows
To test this properly, you will need to have your own tenant you can log into. I tried this locally using my own tenant I just created  and it works if you make this change, and doesn't work without it

CS-2461 - prevent stringed null from being returned

---

apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
apps/tenant-management-webapp/src/app/store/pdf/sagas.ts

This change is to prevent users from pressing the back button in turn it redirects it back to PDF Editor when updating the name and description in the Tombstone by disabling the back button.

Disable back button on update with the tombstone

---

apps/tenant-management-webapp/src/app/pages/admin/services/file/addEditFileTypeDefinitionEditor.tsx
apps/tenant-management-webapp/src/app/store/file/models.ts

Default to Protected A when no security classification is available when they save the file type.

default to ProtectedA for backwards compatability

---

apps/tenant-management-webapp/src/app/store/calendar/sagas.ts

I had accidentally introduced this earlier while testing something

calendar fix - discovered by lana

---

apps/tenant-management-webapp-e2e/src/integration/file-service/file-service.step.ts

Current cypress browserify / tsify preprocessor configuration seems to resolve to the wrong axios bundle based.

fix(tenant-management-webapp-e2e): import axios from dist in test step

---

apps/tenant-management-webapp/src/app/store/metrics/sagas.ts

Increasing page size on service metrics so data for 5 hr window is retrieved.

fix(tenant-management-webapp): increase page size for service metrics

---

apps/push-service/src/push/configuration.ts
apps/push-service/src/push/events.ts

Delete of web-hook currently sets a null instead of removing property; make configuration forgiving to support for now.

fix(push-service): allow null for specific web-hook

---

libs/adsp-service-sdk/src/access/assert.ts
libs/adsp-service-sdk/src/configuration/configurationUpdateHandler.ts
libs/adsp-service-sdk/src/configuration/index.ts

Convention is that roles are qualified with the service ID when the client doesn't match the current service (i.e. roles in other clients). This can't be changed without substantial rework.

fix(adsp-service-sdk): revert unintentional change to role resolution

---

apps/subscriber-app/src/app/pages/private/Subscriptions/ContactInfoCard.tsx
apps/subscriber-app/src/app/pages/validateModal.tsx

Don't allow verification of phone number when there is no phone number 
Previously this would only display an error afterwards, now we hide it entirely

CS-2544 - take into account the no phone case

---

apps/token-handler/src/token/configuration/schema.ts
apps/token-handler/src/token/model/client.spec.ts
apps/token-handler/src/token/model/client.ts
apps/token-handler/src/token/router/client.swagger.yml
apps/token-handler/src/token/router/client.ts
apps/token-handler/src/token/router/session.swagger.yml
apps/token-handler/src/token/router/target.swagger.yml
apps/token-handler/src/token/types.ts
apps/token-handler/swagger.config.js

Disabling verify host is used for local development, as server will not accept x-forwarded- header from outside local.

feat(token-handler): add configuration to disable verify host

---

apps/pdf-service/src/pdf/job/generate.ts
apps/pdf-service/src/pdf/model/template.spec.ts
apps/pdf-service/src/pdf/model/template.ts
libs/adsp-service-sdk/src/configuration/configurationService.ts

ADSP onfiguration capabilities are intended to limit sync coupling using caching, and including bypass breaks that pattern. Direct API use can still circumvent the consumer side caching.
BREAKING CHANGE: cache bypass is no longer available on the configuration service interface.

fix(adsp-service-sdk): removing cache bypass from configuration service

---

apps/script-service/Services/IScriptFunctions.cs
apps/script-service/Services/ScriptFunctions.cs
apps/script-service/Services/StubScriptFunctions.cs
apps/tenant-management-webapp/src/app/lib/luaCodeCompletion.ts

using the api (POST https://calendar-service.adsp-dev.gov.ab.ca/script/v1/scripts/scriptId ) should allow you to send events using the ui allows you to add HttpGet, but will only return a simulated response if you execute it in the ui itself
---- LUA SCRIPT ----
```
local x = adsp.HttpGet("http://postman-echo.com/get")
return x;
```
---------------------

CS-2566 - Get Request Script Function

---

apps/tenant-management-webapp/src/app/components/AppHeader.tsx

* We dispatch an attempted tenant fetch on the mobile app header which causes the following error during tenant creation
* failed to fetch tenant: Cannet read properties of undefined (reading 'id')
* We no longer need this mobile app header in it's entirety - it's never visible because we've disabled mobile view, but it's still being run in the background even when it's not visible. Mostly this doesn't cause any errors, but in this case we're getting an error because we're not logged in
fixes

CS-2634 - failed to fetch tenant

---

apps/tenant-management-webapp/src/app/components/ErrorBoundary.tsx
apps/tenant-management-webapp/src/app/lib/validation/checkInput.ts
apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx

Now, we can see the errors for the jsonforms validation.

Add error boundary to the json forms previous

---

apps/task-app/src/app/state/task.slice.ts

Task changes can affect metrics, so load metrics when there is a task update for the current queue.

feat(task-app): dispatch queue metric load on task update

---

apps/comment-service/src/comment/model/topic.ts
apps/comment-service/src/comment/router/topic.spec.ts
apps/comment-service/src/comment/router/topic.ts

This is to support platform services creating topics. Also, allowing query of topics, but with results filtered to those the user can read.

chore(comment-service): permit core context topic setters

---

apps/comment-service/src/main.ts
apps/task-app/src/app/containers/CommentsViewer.tsx
apps/task-app/src/app/state/comment.slice.ts
apps/task-app/src/app/state/task.slice.ts
apps/task-app/src/app/state/util.ts
apps/task-service/src/comment.ts
apps/task-service/src/main.ts
apps/task-service/src/task/comment.ts
apps/task-service/src/task/configuration.ts
apps/task-service/src/task/index.ts
apps/task-service/src/task/model/queue.ts
apps/task-service/src/task/router/queue.spec.ts
apps/task-service/src/task/router/queue.ts
apps/task-service/src/task/router/task.ts
apps/task-service/src/task/types/queue.ts

Add support for retrieving topic of task and topic of entity associated with task (via recordId) in task app.

feat(task-service, task-app): create task topic when creating a task

---

apps/file-service/src/file/model/file.ts
apps/file-service/src/file/router/file.swagger.yml
apps/file-service/src/file/router/file.ts
apps/file-service/src/file/router/upload.ts
apps/file-service/src/file/types/file.ts
apps/task-app/src/app/state/config.slice.ts

User provided mime type is overwritten if the magic bytes detection determines a value. Cleaning up some extraneous code in file router.
Also, fixing missing id for task app feedback payload.

feat(file-service): allow user to specify the mime type when uploading

---

apps/token-handler/src/token/model/client.ts
apps/token-handler/src/token/model/target.spec.ts
apps/token-handler/src/token/model/target.ts

Split causes a problem when target id appears in another part of the path. Also remove URL.pathname since that strips query params.

fix(token-handler): change how relative request path is determined

---

apps/notification-service/src/notification/model/subscription.spec.ts
apps/notification-service/src/notification/model/subscription.ts
apps/notification-service/src/notification/router/subscription.spec.ts
apps/notification-service/src/notification/router/subscription.swagger.yml
apps/notification-service/src/notification/router/subscription.ts

This is so that clients don't need to read just to remove a criteria object via update.

feat(notification-service): support deletion of a subscription criteria

---

apps/form-service/src/form/model/form.spec.ts
apps/form-service/src/form/model/form.ts
apps/form-service/src/form/model/formSubmission.ts
apps/form-service/src/form/router/form.spec.ts
apps/form-service/src/form/router/form.swagger.yml
apps/form-service/src/form/router/form.ts

Form data and files is accessed via dedicated 'access' operation to enforce permissions based on roles and form lifecycle. Also adding check on form read, since even 'metadata' access should be restricted to users with form related roles.

fix(form-service): remove form data and files from form response

---

apps/task-app/src/app/containers/TaskQueue.tsx
apps/task-app/src/app/containers/TaskQueues.tsx
apps/task-app/src/app/state/task.slice.ts

Basically, we need to
1) ensure not getting a task result is reflected in the tasks and is different than an empty result
2) ensure we are in a good state when we get bounced back to the list page due to incorrect namespace/name route

CS-2917 - Banner no longer prevents details redirection

---

apps/task-service/src/postgres/task.ts
apps/task-service/src/postgres/types.ts
apps/task-service/src/task/events.ts
apps/task-service/src/task/mapper.ts
apps/task-service/src/task/model/task.ts
apps/task-service/src/task/router/queue.ts
apps/task-service/src/task/router/task.spec.ts
apps/task-service/src/task/router/task.ts
apps/task-service/src/task/types/task.ts

Use task associated record ID and fallback to task URN instead of using task ID as the even correlation ID. This will allow task related events to be associated with the other events against the associated entity.

chore(task-service): change task event correlationId

---

apps/comment-service/src/comment/events.ts
apps/comment-service/src/comment/mapper.ts
apps/comment-service/src/comment/router/topic.spec.ts
apps/comment-service/src/comment/router/topic.ts
apps/comment-service/src/comment/types/topic.ts

Use resourceId and fallback to topic URN so that comment events can be correlated with other events against the associated entity.

chore(comment-service): change topic and comment correlationId

---

apps/file-service/src/file/events.ts
apps/file-service/src/file/index.ts
apps/file-service/src/file/job/deleteOldFiles.ts
apps/file-service/src/file/job/index.ts
apps/file-service/src/file/job/scan.spec.ts
apps/file-service/src/file/job/scan.ts
apps/file-service/src/file/mapper.ts
apps/file-service/src/file/model/file.ts
apps/file-service/src/file/router/file.spec.ts
apps/file-service/src/file/router/file.ts
apps/file-service/src/file/router/upload.ts
apps/file-service/src/file/types/file.ts

Also removing some extraneous code for retrieving file type; file type is already retrieved and set on the file entity.

chore(file-service): fallback to file URN for correlationId

---

libs/app-common/src/components/CommentsViewer.tsx

Fallback to empty string in GoATextArea so that the draft is cleared.

fix(task-app, form-app): fix clearing of comment draft

---

apps/value-service/src/values/router/value.spec.ts
apps/value-service/src/values/router/value.ts

Fixing issue where result mapping causes value API to return 500 when there is a write failure; expected is that null is returned for scalar and empty array is returned for batch writes.

fix(value-service): fix destructuring of undefined for failed write

---

apps/script-service/Events/ScriptExecutionFailed.cs
apps/script-service/Services/LuaScriptService.cs
apps/script-service/Services/ScriptFunctions.cs
apps/script-service/Services/StubScriptFunctions.cs

Return inner error message in script failure since the outer exception is always a wrapping LuaScriptException.

feat(script-service): return inner error for net error

---

apps/pii-service/pii_service/app.py
apps/pii-service/pii_service/resources/swagger.yml

Additional language models may be expensive in memory to load, so keep to to en as the required one to support for now.

feat(pii-service): restrict to en for now

---

apps/configuration-service/project.json
apps/configuration-service/src/configuration/index.ts
apps/configuration-service/src/configuration/model/configuration.ts

The loading of configuration definition generally doesn't include the schema, and that shouldn't result in an error.

fix(configuration-service): handle falsy schema

---

apps/configuration-service/src/configuration/router/configuration.spec.ts
apps/configuration-service/src/configuration/router/configuration.ts

Configuration definition is used for the write schema validation, but this is not needed in reads. Add parameter so this extra load can be skipped for read requests.

chore(configuration-service): skip load of definition in reads

---

apps/configuration-service/src/configuration/model/configuration.spec.ts
apps/configuration-service/src/configuration/model/configuration.ts
apps/configuration-service/src/configuration/repository/activeRevision.ts
apps/configuration-service/src/configuration/router/__snapshots__/configuration.spec.ts.snap
apps/configuration-service/src/configuration/router/configuration.spec.ts
apps/configuration-service/src/configuration/router/configuration.ts
apps/configuration-service/src/configuration/types/configuration.ts
apps/configuration-service/src/mongo/activeRevisions.ts
apps/configuration-service/src/mongo/repository.ts

Use property getter for lazy load of active revision from repo instead of always loading as part of entity load. This is to avoid an extra database read when active revision information isn't required (e.g. in the /latest endpoint currently used by the SDK).

chore(configuration-service): lazy load active revision in getter

---

libs/adsp-py-common/adsp_py_common/access.py
libs/adsp-py-common/tests/test_access.py

Handle error in tenant metadata retrieval so that one missing tenant does not cause the cache to fail initialization.

fix(adsp-py-common): handle error in tenant metadata

---

apps/form-app/src/app/state/form.slice.ts
apps/form-app/src/app/state/user.slice.ts
apps/form-service/src/form/router/form.ts

Setting subscriber info from the app is needed since the backend can't assume the user is the applicant (e.g. clerk assisted application).

feat(form-app): use user name and set applicant info for notification

---

apps/feedback-service/project.json
apps/form-service/project.json
apps/form-service/src/form/configuration.ts
apps/form-service/src/form/model/definition.spec.ts
apps/form-service/src/form/model/definition.ts
apps/form-service/src/form/router/form.spec.ts
apps/form-service/src/form/router/form.ts
apps/form-service/src/main.ts
apps/form-service/src/mongo/definition.ts
apps/form-service/src/utils.ts
libs/adsp-service-sdk/src/configuration/configurationService.spec.ts
libs/adsp-service-sdk/src/configuration/configurationService.ts

For transition of configuration, load form definitions from both platform:form-service and form-service namespace.

feat(form-service): load definitions from configuration namespace

---

apps/pdf-service/Dockerfile
apps/pdf-service/project.json
apps/pdf-service/src/puppeteer.ts

Removing separate npm install of puppeteer in container build and use the one included in the copied in build output. Also enabling sandbox since that's recommended.

chore(pdf-service): use puppeteer from node_modules

---

apps/configuration-service/src/mongo/repository.ts

Removing use of let in pipeline lookup stage since it is not supported in CosmosDb.

fix(configuration-service): removing use of unsupported feature

---

apps/configuration-service/src/mongo/repository.ts
apps/configuration-service/src/mongo/types.ts

CosmosDb Mongo API to able to support the subquery needed for a left outer join to revisions. Switching back to two separate requests.

fix(configuration-service): removing use of aggregation pipeline

---

apps/configuration-service/src/configuration/router/__snapshots__/configuration.spec.ts.snap
apps/configuration-service/src/configuration/router/configuration.spec.ts
apps/configuration-service/src/configuration/router/configuration.swagger.yml
apps/configuration-service/src/configuration/router/configuration.ts
apps/configuration-service/src/configuration/router/types.ts
apps/configuration-service/src/mongo/repository.ts

Push check that active revision being set exists down to repository. Skip setting revision when value is the same as the current active revision.

chore(configuration-service): revision operation clean up.

---

apps/notification-service/src/notification/router/subscription.spec.ts
apps/notification-service/src/notification/router/subscription.ts

Signal the subscriber created event when a subscriber is created as part of subscribing to a notification type.

fix(notification-service): signal subscriber created in subscribe

---

apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitions.tsx

This was causing errors related to PayloadTooLargeError exception while saving to the configuration service and partially related to the performance to the editor.
Also fix the data register notification from displaying when no data registers were added.

fix(tenant-management-webapp): duplicate roles in form definition form definition on save

---

apps/form-service/src/form/model/definition.spec.ts
apps/form-service/src/form/model/definition.ts
apps/form-service/src/form/router/form.spec.ts
apps/form-service/src/form/router/form.ts
apps/form-service/src/main.ts

Also, return 410 for definitions endpoint since previous implementation no longer returns correct information.

feat(form-service): allow anonymous access to definition

---

apps/form-service/src/form/model/form.spec.ts
apps/form-service/src/form/model/form.ts
apps/form-service/src/form/types/form.ts
apps/form-service/src/main.ts
apps/form-service/src/mongo/definition.ts
apps/form-service/src/mongo/form.ts
apps/form-service/src/mongo/index.ts
apps/form-service/src/notification.spec.ts
apps/form-service/src/notification.ts

Improving handling around missing definition, and removing retrieval of definition from old configuration location.

fix(form-service): handle missing definition in save

---

libs/adsp-service-sdk/src/access/resolveRoles.spec.ts
libs/adsp-service-sdk/src/access/resolveRoles.ts

Add qualified name for roles of the current service the SDK is initialized against in addition to unqualified name to support cases where a client role of the service is included in configuration. Configuration need to use qualified names for end user configuration experience; otherwise the roles can be ambiguous across different services.

feat(adsp-service-sdk): include qualified service client roles

---

apps/tenant-management-webapp/src/app/lib/autoComplete/form.ts
libs/data-exchange-standard/src/common.v1.schema.json
libs/data-exchange-standard/src/standard.v1.schema.json

Also adjusting patterns to allow empty string. Required property validation will cover required fields, and empty string should be allowed for non-required values. Also including only top level definitions in $ref completion suggestions to simplify use of common schemas.

feat(data-exchange-standard): add common schema for person objects

---

apps/form-app/src/app/state/form.slice.spec.ts
apps/form-app/src/app/state/form.slice.ts

Default data and files values to be empty object consistent with default state.

fix(form-app): support submit of form without files

---

apps/pdf-service/src/pdf/router/pdf.ts

Increase filename size in situations where the pdf template name can be more than 30 characters and ISO time stamp is 23 characters combined as the file name is more than 50 characters.

fix(pdf-service): increase allow filename length size

---

apps/notification-service/src/notification/model/subscription.spec.ts
apps/notification-service/src/notification/model/subscription.ts
apps/notification-service/src/notification/router/subscription.spec.ts
apps/notification-service/src/notification/router/subscription.swagger.yml
apps/notification-service/src/notification/router/subscription.ts

Send a subscription deleted event when the net effect of a criteria removal is unsubscribe. Update the subscription entity criteria in the behaviour so that subscription set event reflects new state of the subscription.

fix(notification-service): send appropriate event for criteria update

---

apps/status-service/src/app/model/index.ts
apps/status-service/src/app/router/notice.ts
apps/status-service/src/app/router/serviceStatus.ts
apps/status-service/src/app/router/spec/notice.spec.ts
apps/status-service/src/app/router/spec/status.spec.ts

Remove direct use of entity in res.send so serializer isn't processing functions and references.

fix(status-service): map entities for response

---

apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx

Removing an item from the array does not automatically update the array's length. The item is removed from the disposition array, but using splice ensures both the array and its length are updated correctly

bug fix for CS-3531 Console error deleting disposition states of a form definition.

---

apps/tenant-management-webapp/src/app/pages/admin/services/events/stream/testStream/streamPayloadTableItem.tsx

Messages can be projection of event, so payload property isn't always applicable.

feat(tenant-management-webapp): change details of stream item

---

apps/directory-service/src/main.ts
apps/form-service/src/form/router/form.ts

Using long configuration cache TTL since event-driven invalidation is enabled. Also making small correction to form service log entry.

chore(directory-service): use event based config invalidation

---

apps/notification-service/src/mongo/schema.ts
apps/notification-service/src/notification/model/type.spec.ts
apps/notification-service/src/notification/model/type.ts

Removed hardcoding of title and subtitle to the values configured on the email channel template.

fix(notification-service): use proper channel title and subtitle

---

apps/form-service/src/form/events.ts
apps/status-service/src/app/events.spec.ts
apps/status-service/src/app/events.ts
apps/tenant-management-webapp/src/app/lib/dynamicPlaceHolder.ts

Enabling use of examples in json schema faker to support configuration of notification templates.

chore: adding examples to event payload schemas

---

apps/calendar-service/src/calendar/router/calendar.ts
apps/calendar-service/src/postgres/calendar.ts

Also making validation forgiving of null for recordId and context.

fix(calendar-service): correct criteria value for activeOn filter

---

.openshift/managed/pdf-service.yml
apps/pdf-service/src/main.ts
tools/workspace-plugin/src/generators/adsp-service/openshift-files/managed/__projectName__.yml__tmpl__

This is to allow generation to continue in case the API pods are stressed by requests. Also, removing unused branch deployment configuration in generator template.

chore(pdf-service): add dedicate job pod

---

apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/eventListFilter.tsx

- Introduced `useEffect` to update start and end date values when `calenderName` changes.
- 
- Added default initialization for `startDate` and `endDate` to current date and 7 days ahead.
- 
- Separated date input field values from the `criteria` object by using `useState` hooks for `startDateValue` and `endDateValue`.
- 
- Updated logic to handle date changes more efficiently by first updating state values before dispatching the updated criteria.

CS-3572 Calendar events shows time range criteria different from value used on request

---

.github/workflows/delivery-ci.yml
apps/file-service/src/scan/clam.ts
apps/notification-service/src/notification/router/subscription.swagger.yml

Add a gate stage in the pipeline to support deployment approval to work around matrix strategy requiring multiple approvals. Also making some adjustments to notification API documentation.

chore: add job for deployment approval

---

apps/notification-service/src/mongo/subscription.ts

Specifically handle case where subscription criteria is stored as a sub document not in an array.

fix(notification-service): handle legacy subscription criteria

---

apps/file-service/src/file/router/file.ts

Include 0 (a falsy value) in content range header if that is the requested start / end.

fix(file-service): handling 0 start or end in range

---

apps/value-service/src/values/router/value.spec.ts
apps/value-service/src/values/router/value.ts

Value service is biased to writing a value even if configuration cannot be retrieved. This means that definition schema is a best effort.

chore(value-service): handle configuration error and write

---

apps/directory-service/src/directory/events.spec.ts
apps/directory-service/src/directory/events.ts
apps/directory-service/src/directory/index.ts
apps/directory-service/src/directory/job/index.ts
apps/directory-service/src/directory/job/resolve.spec.ts
apps/directory-service/src/directory/job/resolve.ts
apps/directory-service/src/directory/model/resource.spec.ts
apps/directory-service/src/directory/model/resource.ts
apps/directory-service/src/main.ts

If resolve encounters a missing resource, then delete it for consistency. Note that the directory resource API does not check if an API resource exists, but the resolve job will delete it after for eventual consistency if an associate type exists.

feat(directory-service): handle missing resource in resolve

---

apps/form-service/src/form/events.ts

Include definition ID so that duration metrics are specific to definitions. i.e. how long does a particular form take to complete rather than how long all forms take to complete.

chore(form-service): definition context in duration metric

---

.openshift/managed/content-service.yml
.vscode/settings.json

This is needed while we're using RWO persistent volume for sql lite database.

chore(content-service): use recreate strategy

---

apps/form-service/src/form/events.ts
apps/form-service/src/form/model/form.ts
apps/form-service/src/form/model/formSubmission.spec.ts
apps/form-service/src/form/model/formSubmission.ts
apps/form-service/src/form/router/form.spec.ts
apps/form-service/src/form/router/form.ts
apps/form-service/src/mongo/form.ts
apps/form-service/src/mongo/formSubmission.ts
apps/form-service/src/mongo/index.ts
apps/form-service/src/mongo/schema.ts

Security classification applies to the specific data in the form or submission record and shouldn't change indirectly via configuration update. Also, update submission repo to load definitions directly since associated forms can be deleted.

fix(form-service): save classification to form and submission

---

apps/form-app/src/app/state/user.slice.ts

This is to allow tenant realm configuration to determine the IDP to use for public users accessing forms.

feat(form-app): remove default idp hint

---

libs/jsonforms-components/src/lib/Controls/AddressLookup/AddressLookUpControl.tsx
libs/jsonforms-components/src/lib/Controls/AddressLookup/types.ts
libs/jsonforms-components/src/lib/Controls/Inputs/InputMultiLineTextControl.tsx
libs/jsonforms-components/src/lib/util/inputControlUtils.ts

Reverting - this feels kind of like a hack anyway - causes some issues with entering data
* We should add documentation that states additional constraints have to be used on strings in order to prevent entering an empty string ('')

fix(empty validation)

---

apps/file-service/src/file/router/file.ts

stream.pipe() has known issues with dangling listeners.

fix(file-service): switch to pipeline interface for stream

---

apps/file-service/src/file/router/file.spec.ts
apps/file-service/src/file/router/file.ts
apps/file-service/src/storage/azure-blob.ts

Catch and log the stream error. It's too late to update the response status since body is already being written by the stream.

chore(file-service): adjust error handling on stream

---

apps/form-service/src/form/configuration.ts
apps/form-service/src/form/model/definition.ts
apps/form-service/src/form/types/definition.ts
apps/form-service/src/mongo/form.ts
apps/form-service/src/mongo/schema.ts
apps/form-service/src/mongo/types.ts

Support for form definitions that permit multiple forms per applicant (when setting is set to false).

feat(form-service): set unique constraint on oneFormPerApplicant config

---

libs/adsp-service-spring-sdk/pom.xml

Need to trigger a release after update of maven semantic release plugin to make up for missed maven publish on spring boot 3 upgrade.

fix(adsp-service-spring-sdk): triggering spring sdk release

---

apps/form-admin-app/src/app/state/form.slice.ts

Need to set default in either form api response or resource api response in case of tag based search.

fix(form-admin-app): set default oneFormPerApplicant

---

apps/push-service/src/push/model/stream.ts

Configuration invalidation using event stream always requires the tenantId for cache invalidation for either platform or tenant services.

fix(push-service): always include tenantId in event

---

apps/configuration-service/src/configuration/router/configuration.ts

Rate limit handler uses callback, so actions directly after need to be in the callback instead of directly run.

fix(configuration-service): move post-rate limit into function

---

apps/form-admin-app/src/lib/validations/checkInput.ts
apps/task-app/src/lib/validations/checkInput.ts
libs/core-common/src/jsonSchema/ajv.ts
libs/jsonforms-components/src/lib/common/Ajv.ts

ajv by default only supports time if a timezone is added
but GoAInputTime itself doesn't support showing the time if a timezone is included in the data
so we would have to add and remove timezones before and after the data is displayed
The alternative is simply to add a simplified time format to ajv - I think this makes more sense in this case - we could do it the other way if we really want to support timezones, but it could add confusion and introduce bugs

fix(time validation) - time is not supported by ajv

---

apps/configuration-service/src/configuration/router/configuration.ts
libs/adsp-service-sdk/src/configuration/configurationService.ts
libs/adsp-service-sdk/src/registration/index.ts
libs/adsp-service-sdk/src/registration/registration.ts
libs/core-common/src/errors/handler.ts

This is to allow registration of form definitions, and other service configuration that use a configuration namespace instead of a single document.

feat(adsp-service-sdk): support name configuration in registration

---

libs/adsp-feedback/src/main.ts

fixes
• Error: This form does not contain a submit button, which creates issues for those who cannot submit the form using the keyboard. Submit buttons are INPUT elements with type attribute "submit" or "image", or BUTTON elements with type "submit" or omitted/invalid.
├── WCAG2AA.Principle3.Guideline3_2.3_2_2.H32.2
├── html > body > div:nth-child(9) > div:nth-child(2) > div > div:nth-child(1) > form
└── <form class="adsp-fb-form"> <h3 class=...</form>

fix(submit button) - change to button to submit for accessibility

---

apps/form-service/src/form/router/form.ts

Replace the create event with the submit even if form is directly submitted on creation.

chore(form-service): send only submit event if submitted on create

---

apps/notification-service/src/notification/router/subscription.spec.ts
apps/notification-service/src/notification/router/subscription.ts

This is required because the endpoint is used without tenant context from the subscriber gateway. In that case, the subscriber tenant Id is the tenant context and needs to be used for configuration retrieval.

fix(notification-service): pass tenantId to getConfiguration

---

libs/jsonforms-components/src/lib/Controls/Inputs/InputBaseReviewControl.tsx
libs/jsonforms-components/src/lib/Controls/Inputs/InputbaseReviewControl.spec.tsx

remove the highlighted text when no data is entered in a text field.

fix(jsonforms-components): remove unnecessary code to display text in review summary

---

libs/jsonforms-components/src/lib/Additional/GoACalloutControl.tsx

1. Correctly wrapping the `GoACalloutController` component with `withJsonFormsControlProps` to ensure proper connection with the JsonForms state and rule engine.
2. Updating `GoACalloutController` to explicitly handle the initial undefined/empty data state, ensuring the callout defaults to hidden.
3. For subsequent state changes (when data is present), the component now correctly uses the `visible` prop, which is derived from the UI schema rule and passed by `withJsonFormsControlProps`.

Fix-CS-4180 Callout does not support show/hide rule condition

---

.openshift/managed/pdf-service.yml

Increase /dev/shm size for the pdf-service-job pod to 1Gi using an emptyDir volume. Puppeteer (Chromium) relies on shared memory for rendering, and the default 64Mi limit can cause crashes (Protocol error: Connection closed) during PDF generation. Mounting a larger /dev/shm improves reliability and performance, especially for templates with complex layouts or large data sets.

fix(pdf generation) - increase memory for chromium

---

apps/configuration-service/src/mongo/repository.ts

Potential fix for [https://github.com/GovAlta/adsp-monorepo/security/code-scanning/155](https://github.com/GovAlta/adsp-monorepo/security/code-scanning/155)
The best way to fix this problem is to ensure that the user-provided configuration data cannot be interpreted as a query operator object by MongoDB. You can do this by "defensively" wrapping the configuration data in a way that MongoDB only treats it as a literal value (using the `$set` update operator in an update context) or by thoroughly checking that the configuration does not include any property names that start with `$`. Given this is an `update` payload in a `findOneAndUpdate` call (not the filter), you must ensure the user-provided object is not used in a way that allows dangerous operators. Specifically, the `configuration` …

Potential fix for code scanning alert no. 155: Database query built from user-controlled sources

---

apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitions.tsx

Updated the condition to display the 'Load More' button so it only appears when neither ministryFilter nor programFilter are set. This prevents loading more entries when filters are active.

fix-CS-4380-As a form designer I can search for all form definitions associated with a program

---

.openshift/managed/event-service.yml

This with local reference policy avoids direct requests to docker hub.

chore(event-service): using imagestream for statefulset images

---

apps/notification-service/src/notification/job/processEvent.ts

Sending on no more retries doesn't generally work since the try catch is preventing the overall generation job from failing.

fix(notification-service): send generation failed on first failure
