- apps/tenant-management-webapp-e2e/src/integration/notifications.feature
- apps/tenant-management-webapp-e2e/src/integration/notifications/notifications.page.ts
- apps/tenant-management-webapp-e2e/src/integration/notifications/notifications.step.ts
- apps/tenant-management-webapp-e2e/src/integration/service-status.feature
- apps/tenant-management-webapp-e2e/src/integration/service-status/service-status.step.ts
Automated test for core notification type event email template overwrite
> Automated test for core notification type event email template overwrite

- .github/workflows/codeql-analysis.yml
- .github/workflows/image-clean-up.yml
Trying build via nx for codeql.
> chore: updating some github workflows for image clean up and codeql

- apps/status-service/src/app/amqp/HealthCheckController.ts
before switch, and let the default case handle it.
> fix(status-service): remove test for null

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypeModal.tsx
> CS-1662 - file type validation becomes case insensitive

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarsView.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/styled-components.ts
- apps/tenant-management-webapp/src/app/store/calendar/models.ts
- apps/tenant-management-webapp/src/app/store/calendar/sagas.ts
> fix:cs-580 UI improvement

- apps/tenant-management-webapp/src/app/pages/admin/event-log/eventSearchForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/events/definitionsList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/events/stream/addEditStream/addEditStream.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/events/stream/streamTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/events/stream/testStream/testStream.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/editEvent.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/notificationTypes.tsx
> feat:order event in tenant management webapps

- apps/tenant-management-webapp/src/app/pages/admin/dashboard/dashboard.tsx
> feat: update the side bar in the dashboard

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templateListItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templates.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templatesList.tsx
- apps/tenant-management-webapp/src/app/store/pdf/action.ts
- apps/tenant-management-webapp/src/app/store/pdf/reducers.ts
- apps/tenant-management-webapp/src/app/store/pdf/sagas.ts
> feat: cs-1636 remove pdf templates

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/styled-components.ts
> fix:cs-580 calendar view table improvement

- apps/tenant-management-webapp/src/app/components/icons/ExternalLink.tsx
- apps/tenant-management-webapp/src/app/pages/admin/dashboard/dashboard.tsx
> update the link in tenant admin webapp

- apps/tenant-management-webapp/src/app/components/icons/ExternalLink.tsx
- apps/tenant-management-webapp/src/app/pages/admin/dashboard/dashboard.tsx
> feat: update the external link

- apps/tenant-management-webapp/src/app/pages/admin/dashboard/dashboard.tsx
> Update the copy link tooltip

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templates.tsx
> fix: pdf-delete-modal ui issue

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarsView.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templateListItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templates.tsx
- apps/tenant-management-webapp/src/app/store/calendar/actions.ts
- apps/tenant-management-webapp/src/app/store/calendar/models.ts
- apps/tenant-management-webapp/src/app/store/calendar/reducers.ts
- apps/tenant-management-webapp/src/app/store/calendar/sagas.ts
> feat: cs-1652 edit calendars

- libs/adsp-service-net-sdk/Tenancy/TenantService.Spec.cs
> CS-1627 - Tenancy tests

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarList.tsx
- apps/tenant-management-webapp/src/app/store/calendar/actions.ts
- apps/tenant-management-webapp/src/app/store/calendar/reducers.ts
- apps/tenant-management-webapp/src/app/store/calendar/sagas.ts
> add delete function to calendar

- apps/status-service/src/app/amqp/HealthCheckController.ts
- apps/status-service/src/app/jobs/JobScheduler.spec.ts
- apps/status-service/src/app/jobs/JobScheduler.ts
- apps/status-service/src/app/model/applicationManager.ts
- apps/status-service/src/main.ts
When starting an application health check
> fix: get application data from cache

- libs/notification-shared/src/getTemplateBody.ts
> update the pdf template

- apps/status-service/src/app/router/serviceStatus.ts
- apps/status-service/src/app/router/spec/status.spec.ts
> CS-1719 - don't show internal fields

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/generatePDFModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/testGenerate.tsx
resize headers on test generate
> split footer/header in half, add titles

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarList.tsx
> CS-1709 - don't show table of calendar to be deleted

- apps/pdf-service/src/file.ts
- apps/subscriber-gateway/src/subscriber/router.ts
> CS-1691 - Fix Critical security issues pointed out by github

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/export/export.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/import/import.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/styled-components.ts
> CS-1580 - Redesign - according to comments made by Zion

- apps/status-service/src/app/router/serviceStatus.ts
> fix: add _id back to GET applications

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/styled-components.ts
> remove comment and resize - we always apply formatting

- libs/adsp-service-net-sdk/Registration/ServiceRegistrar.Spec.cs
- libs/adsp-service-net-sdk/Registration/ServiceRegistrar.cs
> adsp-net-service-sdk: Service registrar unit tests

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/import/import.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/styled-components.ts
* Checkmark no longer shrinks on hover
* background goes dark blue on hover if checked
* Change import button on import page to use new button design
* Choose a file button on import page background is now correctly slightly grey
> CS-1580 - Re-re-redesign - just some minor tweaks

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/AddScriptModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/script.spec.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/script.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/scriptList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/scriptsView.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
- apps/tenant-management-webapp/src/app/store/reducers.ts
- apps/tenant-management-webapp/src/app/store/sagas.ts
- apps/tenant-management-webapp/src/app/store/script/actions.ts
- apps/tenant-management-webapp/src/app/store/script/models.ts
- apps/tenant-management-webapp/src/app/store/script/reducers.ts
- apps/tenant-management-webapp/src/app/store/script/sagas.ts
> feat: cs-1656  create a script

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/export/export.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/import/import.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/import/jobList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/styled-components.ts
> CS-1580 - fix column width / categorize columns

- apps/status-service/src/app/router/serviceStatus.ts
- apps/status-service/src/app/router/spec/status.spec.ts
for all status-service endpoints that return application data
> fix: use consistent status/configuration merging technique

- apps/tenant-management-webapp/src/app/pages/admin/services/script/AddScriptModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
> fix:script modal ui improvement

- apps/tenant-management-webapp/src/app/pages/admin/services/script/scriptList.tsx
- apps/tenant-management-webapp/src/app/store/calendar/sagas.ts
- apps/tenant-management-webapp/src/app/store/script/actions.ts
- apps/tenant-management-webapp/src/app/store/script/reducers.ts
- apps/tenant-management-webapp/src/app/store/script/sagas.ts
> feat: cs-1658  delete a script

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/export/export.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/styled-components.ts
* Some minor padding changes
* change selected configuration headers for padding bottom/top to 16/8 / style to h3 -> h4
* Selected Configuration to bold
* Added overflow:anywhere to headers so whole header is visible but split between lines if necessary
> Minor changes - Zion

- apps/directory-service/src/directory/router/directory.ts
- apps/status-app/src/app/lib/inputValidation.ts
- apps/status-app/src/app/pages/status.tsx
- apps/status-app/tsconfig.json
- apps/subscriber-app/src/app/pages/private/Subscriptions/ContactInfoCard.tsx
- apps/tenant-management-webapp/src/app/lib/inputValidation.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/status/contactInformation/editContactInfo.tsx
Email - https://stackoverflow.com/questions/42687979/email-validation-regular-expression-is-causing-catastrophic-backtracking
> CS-1693 - High CodeQL errors

- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/notificationTypes.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- libs/notification-shared/src/templates/pdf-footer-wrapper.hbs
- libs/notification-shared/src/templates/pdf-header-wrapper.hbs
> Update the email and pdf editor

- apps/tenant-management-webapp/src/app/components/saveModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/config.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/scriptList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/scriptsView.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
- apps/tenant-management-webapp/src/app/store/script/models.ts
> feat: first commit on edit script

- apps/tenant-management-webapp/src/app/pages/admin/services/script/addScriptModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/scriptList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/scriptsView.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
- apps/tenant-management-webapp/src/app/store/script/sagas.ts
> feat: edit script

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/styled-components.ts
> Update pdf template badge style

- apps/subscriber-app/src/app/app.tsx
- apps/subscriber-app/src/app/pages/public/Login.tsx
- apps/subscriber-app/src/app/pages/public/Subscriptions.tsx
- apps/subscriber-app/src/app/privateApp.tsx
- apps/subscriber-app/src/app/publicApp.tsx
- apps/subscriber-app/src/app/store/tenant/sagas.ts
- package-lock.json
- package.json
Upgrade subscriber app router
Update
> Update the subscriber app router

- apps/script-service/Controllers/ScriptController.cs
scripts/clearCache conflicts with scripts/*
> {"error":"Script definition with ID 'clearCache' not found."}

- .gitignore
- apps/tenant-management-webapp/src/app/store/config/sagas.ts
> fix: allow tenant-management-webapp to override directory service

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/AddEditPdfTemplates.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PDFConfigForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templates.tsx
> update the the pdf template editor

- apps/tenant-management-webapp/src/app/components/Tabs.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PDFConfigForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/styled-components.ts
> adjust the layout of the pdf template editor

- apps/tenant-management-webapp/src/app/store/file/sagas.ts
- apps/tenant-management-webapp/src/app/store/pdf/reducers.ts
>  file types are sorted alphabetically

- apps/status-service/src/app/index.ts
- apps/status-service/src/app/jobs/JobScheduler.spec.ts
- apps/status-service/src/app/model/applicationManager.ts
- apps/status-service/src/app/model/spec/applicationManager.spec.ts
- apps/status-service/src/app/model/statusApplications.ts
- apps/status-service/src/app/router/serviceStatus.ts
- apps/status-service/src/app/router/spec/status.spec.ts
- apps/status-service/src/main.ts
- apps/tenant-management-webapp/src/app/store/status/models.ts
- apps/tenant-management-webapp/src/app/store/status/reducers.ts
by removing repo orphans; those without a corresponding configuration.
> fix: add code to synchronize status service config and repo

- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/scriptsView.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
- apps/tenant-management-webapp/src/app/store/script/sagas.ts
> fix: script editor change layout

- apps/status-service/src/app/model/applicationManager.ts
- apps/status-service/src/app/router/serviceStatus.ts
> fix: allow app to display apps with bad data

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/definitions/definitionsList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/utils.ts
> fix: sorting config definitions by namespaces and names

- apps/tenant-management-webapp/src/app/lib/checkInput.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
- apps/tenant-management-webapp/src/app/store/script/models.ts
- apps/tenant-management-webapp/src/app/store/script/sagas.ts
> fix: script-service editor UI improvement

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/styled-components.ts
- libs/notification-shared/src/templates/email-wrapper.hbs
- libs/stylesheets/scss/src/lib/app.css
> UI touch-up in tenant admin webapp

- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
- apps/tenant-management-webapp/src/app/store/script/models.ts
- apps/tenant-management-webapp/src/app/store/script/sagas.ts
> fix: script-editor layout and add skeleton loading

- apps/tenant-management-webapp/src/app/store/file/reducers.ts
> feat:Test files uploaded file added to top of the list

- apps/status-app/src/app/pages/status.tsx
- apps/subscriber-app/src/app/components/AppHeader.tsx
> Removed beta label from status and subscriber apps

- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
> fix:script-editor response table

- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
> fix:script-editor UI adjust

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/configuration.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisions.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisionsTable.tsx
- apps/tenant-management-webapp/src/app/store/configuration/action.ts
- apps/tenant-management-webapp/src/app/store/configuration/model.ts
- apps/tenant-management-webapp/src/app/store/configuration/reducers.ts
- apps/tenant-management-webapp/src/app/store/configuration/sagas.ts
> feat: view configuration revisions

- apps/tenant-management-webapp/src/app/pages/admin/event-log/eventSearchForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
> fix:event log search box open screen shift issue

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisions.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisionsTable.tsx
> Update configuration revision date

- apps/tenant-management-webapp/src/app/lib/timeUtil.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisionsTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/noticeCard.tsx
> fix: revision time format with at

- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/styled-components.ts
> feat: script editor response table change as header fixed table.

- apps/tenant-management-webapp/src/app/pages/admin/dashboard/dashboard.tsx
- apps/tenant-management-webapp/src/app/pages/admin/dashboard/styled-components.ts
> tenant-web: Dashboard, removed the beta message and added support links

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisionsTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/events/overview.tsx
- apps/tenant-management-webapp/src/app/store/configuration/action.ts
- apps/tenant-management-webapp/src/app/store/configuration/model.ts
- apps/tenant-management-webapp/src/app/store/configuration/reducers.ts
- apps/tenant-management-webapp/src/app/store/configuration/sagas.ts
> feat:create a new revision

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/styled-components.ts
> Update the test space layout

- apps/tenant-management-webapp/src/app/lib/timeUtil.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisions.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisionsTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/noticeCard.tsx
- apps/tenant-management-webapp/src/app/store/configuration/reducers.ts
> fix: loading indication, time format, duplicate item

- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
- apps/tenant-management-webapp/src/app/store/script/models.ts
Now, clicking the "Execute" button in the run script page will not save the script.
> Update the run script frontend

- apps/tenant-management-webapp/src/app/pages/public/Landing.tsx
> Update the ui component card

- apps/configuration-service/src/configuration/router/configuration.spec.ts
- apps/configuration-service/src/configuration/router/configuration.ts
- apps/tenant-management-webapp/src/app/lib/luaCodeCompletion.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
> feat: edit script with autocompletion for adsp

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisionsTable.tsx
- apps/tenant-management-webapp/src/app/store/configuration/action.ts
- apps/tenant-management-webapp/src/app/store/configuration/model.ts
- apps/tenant-management-webapp/src/app/store/configuration/reducers.ts
- apps/tenant-management-webapp/src/app/store/configuration/sagas.ts
> feat: set the active revision

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisionsTable.tsx
> fix:changed the power icon as set active

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/styled-components.ts
> fix the pdf editor action button layout issue

- apps/tenant-management-webapp/src/app/lib/luaCodeCompletion.ts
> fix: add adsp prefix in lua auto complete

- apps/tenant-management-webapp/src/app/pages/admin/dashboard/dashboard.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/import/import.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisionEditModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/revisions/revisionsTable.tsx
- apps/tenant-management-webapp/src/app/store/configuration/action.ts
- apps/tenant-management-webapp/src/app/store/configuration/model.ts
- apps/tenant-management-webapp/src/app/store/configuration/reducers.ts
- apps/tenant-management-webapp/src/app/store/configuration/sagas.ts
> feat:edit the latest revision of non-platform namespace definitions

- .github/workflows/artillery.yml
- tests/artillery.csv
- tests/artillery.dev.csv
- tests/events-service/load.yml
- tests/my-functions.js
just a test github action for running performance tests with artillery for event service
> Added github action for an artillery test

- apps/tenant-management-webapp/src/app/components/Overview/Overview.spec.tsx
- apps/tenant-management-webapp/src/app/components/Overview/Overview.tsx
- apps/tenant-management-webapp/src/app/components/Overview/OverviewLayout.tsx
- apps/tenant-management-webapp/src/app/components/Overview/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/access/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/directory/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileOverview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/overview.tsx
> Add the overall component to tenant-admin

- libs/notification-shared/src/templates/pdf-wrapper.hbs
> up the pdf template wrapper

- apps/tenant-management-webapp-e2e/src/integration/configuration-service/configuration-service.page.ts
- apps/tenant-management-webapp-e2e/src/integration/configuration-service/configuration-service.step.ts
- apps/tenant-management-webapp-e2e/src/integration/notifications/notifications.page.ts
- apps/tenant-management-webapp-e2e/src/integration/notifications/notifications.step.ts
- apps/tenant-management-webapp/src/app/app.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/pdfTemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templates.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/utils/suggestion.ts
- apps/tenant-management-webapp/src/app/pages/editor/editor.tsx
- apps/tenant-management-webapp/src/app/pages/editor/index.tsx
- apps/tenant-management-webapp/src/app/pages/editor/pdf/index.tsx
> Cs 1931 Change PDF template editor to show a full screen editor instead of a modal

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
> fix: page close button to back

- libs/notification-shared/src/templates/pdf-wrapper.hbs
Reverts GovAlta/adsp-monorepo#1465
> Revert "up the pdf template wrapper"

- libs/notification-shared/src/templates/pdf-footer-wrapper.hbs
- libs/notification-shared/src/templates/pdf-header-wrapper.hbs
Reverts GovAlta/adsp-monorepo#1473
> Revert "update footer and header template"

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/editor/scriptEditor.tsx
> fix the save button state issue in the pdf and script pdf edit

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/pdfTemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/testGenerate/generatePDF.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/testGenerate/generatedPdfList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/testGenerate/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/script/addScriptModal.tsx
https://user-images.githubusercontent.com/58053108/215902195-935461e5-0489-4117-ad05-6dd69b4f9249.mov
Screen Recording 2023-01-31 at 3.47.36 PM
> feat: cs-1905 Add tab to manage Variable Assignments when editing PDF

- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/subscribers/subscriberList.tsx
- apps/tenant-management-webapp/src/app/store/subscription/actions.ts
- apps/tenant-management-webapp/src/app/store/subscription/models.ts
- apps/tenant-management-webapp/src/app/store/subscription/reducers.ts
- apps/tenant-management-webapp/src/app/store/subscription/sagas.ts
[demo.webm](https://user-images.githubusercontent.com/31360331/219108729-79e94a31-9141-439f-8c87-4f7ef6bf3186.webm)
> Added new actions in subscriptions redux to toggle show/hide subscriptions

- apps/tenant-management-webapp-e2e/src/integration/pdf-service/pdf-service.page.ts
- apps/tenant-management-webapp-e2e/src/integration/pdf-service/pdf-service.step.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/pdfTemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
> Put header and footer in separate tabs in PDF editor

- apps/tenant-management-webapp/src/app/privateApp.tsx
Reverts GovAlta/adsp-monorepo#1496
> Revert "Add router based header"

- apps/subscriber-app/src/app/pages/private/Subscriptions/Subscriptions.tsx
- apps/subscriber-app/src/app/pages/public/Subscriptions.tsx
- apps/subscriber-app/src/app/store/subscription/sagas.ts
> make skeleton loader go away after load if we don't have data

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/addEditPdfTemplates.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PDFConfigForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templateListItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templates.tsx
> feat:Add edit modal for PDF template name and description

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
> should fix issue where button was within the text box

- apps/pdf-service/src/pdf/configuration.ts
- apps/pdf-service/src/pdf/model/template.ts
- apps/pdf-service/src/pdf/types.ts
- apps/pdf-service/src/puppeteer.spec.ts
- apps/pdf-service/src/puppeteer.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/notificationTypes.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/pdfTemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/store/pdf/model.ts
- apps/tenant-management-webapp/src/app/store/pdf/sagas.ts
- globalConfig.json
> CS-1956-1976

- apps/subscriber-app/src/app/store/subscription/sagas.ts
- apps/subscriber-gateway/src/subscriber/router.ts
> subscriber-app: fixed 404 error check

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/pdfTemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/testGenerate/generatePDF.tsx
- apps/tenant-management-webapp/src/app/store/pdf/model.ts
> feat:Move Generate PDF button to top of Preview panel

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
> more ui tweaks - pass 3

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/generatedPdfList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/store/pdf/action.ts
- apps/tenant-management-webapp/src/app/store/pdf/reducers.ts
- apps/tenant-management-webapp/src/app/store/pdf/sagas.ts
> CS-2055 - delete / delete all / viewing/eye

- apps/tenant-management-webapp/src/app/lib/validation/checkInput.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/addEditPdfTemplates.tsx
- apps/tenant-management-webapp/src/app/store/pdf/sagas.ts
> fix: add template name duplication validation

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
> reduce bar length by 1 pixed

- apps/subscriber-app/src/app/pages/private/Subscriptions/Subscriptions.tsx
- apps/subscriber-app/src/app/pages/public/Subscriptions.tsx
> if contact information is not set, show just a need help box

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/store/pdf/model.ts
- apps/tenant-management-webapp/src/app/store/pdf/reducers.ts
Before it would try to reload to fetch for the file regardless of which template you were on. This fixes it
> CS-2062 - prevent file reload on non-generated template

- libs/adsp-service-flask-sdk/.releaserc.json
- libs/adsp-service-flask-sdk/README.md
- workspace.json
Adding release target and configuration
> feat(adsp-service-flask-sdk): initial implementation of SDK for Flask

- apps/subscriber-app/src/app/pages/private/Subscriptions/Subscriptions.tsx
- apps/subscriber-app/src/app/privateApp.tsx
- apps/subscriber-app/src/main.tsx
[subsccriber-app.webm](https://user-images.githubusercontent.com/31360331/228913901-6e3949f4-8c6e-4b7e-84bd-939fef836430.webm)
> subscriber-app: moved keycloak token fetch call into subscriptions container

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/store/pdf/action.ts
- apps/tenant-management-webapp/src/app/store/pdf/reducers.ts
- apps/tenant-management-webapp/src/app/store/pdf/sagas.ts
* Can now save changes to Test Data in PDF Editor
* Bonus fixes
* Generate now greys out the save button and no longer asks to save, accurately reflecting the save the is implicitly happending
* Fixed a change that caused a PDF template refresh on Save
> CS-2070 Cannot save changes to Test Data

- apps/tenant-management-webapp/src/app/pages/admin/services/directory/modals/deleteModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/directory/modals/editModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/directory/serviceList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/directory/services.tsx
- apps/tenant-management-webapp/src/app/store/directory/models.ts
- apps/tenant-management-webapp/src/app/store/directory/selectors.ts
- apps/tenant-management-webapp/src/app/store/session/actions.ts
- apps/tenant-management-webapp/src/app/store/session/models.ts
- apps/tenant-management-webapp/src/app/store/session/reducers.ts
- apps/tenant-management-webapp/src/app/store/session/selectors.ts
update the directory service
clean lint
> Update the tenant admin web directoy service

- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileList.tsx
- apps/tenant-management-webapp/src/app/store/file/actions.ts
- apps/tenant-management-webapp/src/app/store/file/api.ts
- apps/tenant-management-webapp/src/app/store/file/models.ts
- apps/tenant-management-webapp/src/app/store/file/sagas.ts
User can select from the file types in the tenant
User can search files based on the selected file type
User can clear the file type search criteria, so that files of all types are returned
> CS-2061 - Filter test files by file type

- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileList.tsx
* Title resize
* Blue button
* Put dropdown / filter below each other
* No longer shows File table if no files found
> Some small fixes

- libs/adsp-service-spring-sdk/src/main/java/ca/ab/gov/alberta/adsp/sdk/access/AccessJwtGrantedAuthoritiesConverter.java
- libs/adsp-service-spring-sdk/src/test/java/ca/ab/gov/alberta/adsp/sdk/access/AccessJwtGrantedAuthoritiesConverterTests.java
when accessing roles and realms
> fix(adsp-service-spring-sdk): check for null

- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypeModal.tsx
- apps/tenant-management-webapp/src/app/store/file/models.ts
- apps/tenant-management-webapp/src/app/store/file/sagas.ts
> Add the retention UI to file type

- apps/tenant-management-webapp/src/app/pages/admin/services/status/applications/application.tsx
> CS-2098 - move button

- apps/pdf-service/src/pdf/configuration.ts
- apps/pdf-service/src/pdf/model/template.ts
- apps/pdf-service/src/pdf/types.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/addEditPdfTemplates.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/preview.spec.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templateList.spec.tsx
- apps/tenant-management-webapp/src/app/store/pdf/model.ts
> CS-2097 - checkbox for ADSP default template

- apps/file-service/src/file/job/deleteOldFiles.ts
* Events now show retention days correctly
* Correctly counting number of events now in log
> CS-2038 - Events show retention days

- .openshift/managed/file-service.yml
- apps/file-service/src/environments/environment.ts
- apps/file-service/src/file/job/index.ts
- apps/file-service/src/main.ts
- workspace.json
Reverts GovAlta/adsp-monorepo#1659
> Revert "CS-2040"

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
> CS-2097 - fix spacing

- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypeModal.tsx
> Update the file type retention policy tooltip

- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypeModal.tsx
> update the file type UI

- apps/push-service/src/push/configuration.ts
> add webhooks to pushservice configuration

- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypeModal.tsx
Reverts GovAlta/adsp-monorepo#1724
> Revert "Update the file policy retention UI"

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
- apps/tenant-management-webapp/src/app/store/pdf/model.ts
- apps/tenant-management-webapp/src/app/store/pdf/reducers.ts
> Add the error response to the PDF generation

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/store/pdf/reducers.ts
> Disable pdf generator when test data have errors

- apps/form-service/src/form/events.ts
- apps/form-service/src/form/router/form.spec.ts
- apps/form-service/src/form/router/form.swagger.yml
- apps/form-service/src/form/router/form.ts
- apps/form-service/src/main.ts
Also, adding more lifecycle events for forms.
> feat(form-service): adding service metrics and benchmarks

- apps/push-service/src/push/router/stream.ts
- apps/status-service/src/mongo/schema.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/status/testWebhook.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhooks/webhooks.tsx
- apps/tenant-management-webapp/src/app/store/status/actions/fetchWebhooks.ts
- apps/tenant-management-webapp/src/app/store/status/actions/saveWebhook.ts
- apps/tenant-management-webapp/src/app/store/status/api.ts
- apps/tenant-management-webapp/src/app/store/status/models.ts
- apps/tenant-management-webapp/src/app/store/status/reducers.ts
- apps/tenant-management-webapp/src/app/store/status/sagas.ts
* Some ui fixes in test window
* Filled in some missing information in webhook event
> CS-2088 - WaitTime now is saved in status configuration

- apps/tenant-management-webapp/src/app/pages/admin/services/status/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/status/testWebhook.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhookForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhookHistoryForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhooks/webhookDeleteModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhooks/webhooks.tsx
> webhook ui fixes CS-2094/CS-2095/CS-2096

- apps/tenant-management-webapp/src/app/pages/admin/services/status/status.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhookForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhooks/webhooks.tsx
* or if empty - ie not defined in a test
* Removed some extra code  / renamed no webhooks
> CS-2176 - don't try to display the webhooks before they're loaded

- apps/push-service/src/push/model/stream.spec.ts
- apps/push-service/src/push/model/stream.ts
Add unit tests to verify behaviour.
> fix(push-service): correct the context criteria logic

- apps/tenant-management-webapp/src/app/pages/admin/services/status/testWebhook.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhookForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhookHistoryForm.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhooks/webhookDeleteModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhooks/webhooks.tsx
> Cs 2095 UI 2

- apps/form-service/src/form/configuration.ts
- apps/form-service/src/form/model/form.spec.ts
- apps/form-service/src/form/model/form.ts
- apps/form-service/src/form/router/form.swagger.yml
- apps/form-service/src/form/router/form.ts
Also supporting 'sparse' request body in form data put request.
> fix(file-service): stricter validation of form files property

- apps/tenant-management-webapp/src/app/pages/admin/services/status/testWebhook.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/webhookForm.tsx
> CS-2191 - Limit testing to selected events

- apps/file-service/src/file/job/deleteOldFiles.ts
Change the date query in file retention to ISO8061
> update file retention query format

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/store/pdf/selectors.ts
* Fixed the bug that after clicked the "Generate PDF" button, the save button is still inactive state.
* Fix the preview template sync bug.
> update the state management in the PDF service

- apps/file-service/src/file/job/deleteOldFiles.ts
1. Skip file retention check for file type without file retention.
2. Query the files to be deleted based on file type.
> Update the file retention query

- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileList.tsx
- apps/tenant-management-webapp/src/app/store/file/sagas.ts
- apps/tenant-management-webapp/src/app/store/session/selectors.ts
> Add state to track the file loading state

- apps/file-service/src/mongo/index.ts
Reverts GovAlta/adsp-monorepo#1829
> Revert "Add temp log for the file service"

- apps/tenant-management-webapp/src/app/pages/admin/services/status/applications/application.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/status/form.tsx
- apps/tenant-management-webapp/src/app/store/status/models.ts
[screencast-localhost_4200-2023.07.19-10_11_09.webm](https://github.com/GovAlta/adsp-monorepo/assets/31360331/95a21c04-14b3-47e0-a6ff-f0d7d5b2098d)
> tenant-web: fix: setting status of the new app to none

- apps/tenant-management-webapp/src/app/store/pdf/action.ts
- apps/tenant-management-webapp/src/app/store/pdf/reducers.ts
- apps/tenant-management-webapp/src/app/store/pdf/sagas.ts
Previously, code was not distinguishing between different templates on deletion
> CS-2092 - do not show generated pdfs of other templates

- apps/pdf-service/src/pdf/job/generate.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/PreviewTemplate.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/store/pdf/reducers.ts
- libs/adsp-service-sdk/src/configuration/configurationService.ts
Additional bugs fixed
* Refreshing a template should now work correctly, instead of showing a blank template
* Editing a template no longer causes the preview pane to be refreshed unnnecessarily
> CS-2198 - Generate should now reflect updates every time

- apps/tenant-management-webapp/src/app/pages/admin/services/events/stream/addEditStream/addEditStream.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/events/stream/addEditStream/rolesTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/events/stream/streamTableItem.tsx
- apps/tenant-management-webapp/src/app/store/stream/models.ts
* Make sure that subscriberRoles is nullable in the frontend
> Update the frontend push service schema

- .github/workflows/codeql-analysis.yml
* Add a simple retry for the CodeQL action
> Add retry for the code analysis

- apps/tenant-management-webapp/src/app/lib/autoComplete.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/utils/suggestion.ts
> feat:template configuration provides auto completion of data structure

- apps/pdf-service/src/puppeteer.ts
- package-lock.json
- package.json
Update puppeteer to version 20.9 and fix Jest test file.
> update puppeteer to latest version

- apps/pdf-service/src/puppeteer.ts
- package-lock.json
- package.json
Reverts GovAlta/adsp-monorepo#1863
> Revert "update puppeteer to latest version"

- apps/pdf-service/src/handlebars.ts
- apps/pdf-service/src/pdf/job/generate.spec.ts
- apps/pdf-service/src/pdf/job/generate.ts
- apps/pdf-service/src/pdf/model/template.spec.ts
- apps/pdf-service/src/pdf/model/template.ts
- apps/pdf-service/src/pdf/types.ts
- apps/tenant-management-webapp/src/app/lib/autoComplete.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/utils/suggestion.ts
> CS-2213 - Simplify fileId helper

- apps/tenant-management-webapp/src/app/pages/admin/dashboard/dashboard.tsx
- apps/tenant-management-webapp/src/app/pages/admin/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/form.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/formOverview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/sidebar.tsx
---The overview tab looks correct once a second tab is added ---
> CS-1847 - Form overview

- .openshift/managed/pdf-service.yml
> Increase the resources limit for the pdf service

- apps/pdf-service/Dockerfile
Update the pdf service dockerfile
> Update the pdf service dockerfile

- apps/pdf-service/src/puppeteer.ts
- libs/notification-shared/src/templates/pdf-footer-wrapper.hbs
- libs/notification-shared/src/templates/pdf-header-wrapper.hbs
Modify pdf generation to include background colors for header and footer.
> Cs 2276 css pdf

- apps/pdf-service/Dockerfile
- apps/pdf-service/src/puppeteer.ts
- package-lock.json
- package.json
Reverts GovAlta/adsp-monorepo#1905
> Revert "feat: update the puppeteer version"

- apps/tenant-management-webapp/src/app/store/form/model.ts
> validation fail fix again

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/pdfTemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
> reduce height restriction to 630 pixels, add scrollbar, move hr

- apps/tenant-management-webapp/src/app/pages/admin/services/form/form.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/task/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/task/task.tsx
- apps/tenant-management-webapp/src/app/pages/public/Landing.tsx
To resolve the issues mentioned in the  https://goa-dio.atlassian.net/browse/CS-2298
> Add the beta icon to form and task services

- apps/tenant-management-webapp-e2e/src/integration/file-service/file-service.step.ts
- apps/tenant-management-webapp-e2e/src/integration/pdf-service/pdf-service.page.ts
- apps/tenant-management-webapp-e2e/src/integration/pdf-service/pdf-service.step.ts
- apps/tenant-management-webapp-e2e/src/integration/service-status.feature
- apps/tenant-management-webapp-e2e/src/integration/tenant-admin/tenant-admin.page.ts
> More e2e test updates

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
Added parameter when saving pdf template to not refresh pdf template in Redux so that url redirects with be completed.
> Cs 2324 pdf editor

- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/editEvent.tsx
Fixes for the Next and Cancel buttons not saving dropdown selection in the use state properly.
> Fix Event Modal Next button not triggering

- apps/tenant-management-webapp/src/app/components/RoleTable.tsx
- apps/tenant-management-webapp/src/app/components/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/form/styled-components.ts
> fix table headers and spacing

- apps/tenant-management-webapp/src/app/components/RoleTable.tsx
- apps/tenant-management-webapp/src/app/components/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/form/styled-components.ts
- package-lock.json
> replace table with goa-table and related styling

- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/subscription/subscriptionList.tsx
> Cs 2338 subscriptions

- apps/tenant-management-webapp/src/app/components/RoleTable.tsx
- apps/tenant-management-webapp/src/app/components/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/form/styled-components.ts
Can't seem to override table width in any other way other than setting the table width
> fix styling according to request

- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypeModal.tsx
- apps/tenant-management-webapp/src/app/store/file/models.ts
> CS 2379/2380 file type modal

- apps/tenant-management-webapp/src/app/store/config/models.ts
- apps/tenant-management-webapp/src/featureFlag.ts
> fix task service

- apps/tenant-management-webapp/src/app/components/RoleTable.tsx
- apps/tenant-management-webapp/src/app/components/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/formConfigDefinition.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/styled-components.ts
> fix spacing, fix edit button

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitionsList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/formDefinitionItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/styled-components.ts
> CS-2169 - added roles and schema details

- apps/tenant-management-webapp/src/app/pages/admin/services/task/queueTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/task/queueTableItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/task/queuesList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/task/styled-components.ts
- apps/tenant-management-webapp/src/app/store/reducers.ts
- apps/tenant-management-webapp/src/app/store/sagas.ts
- apps/tenant-management-webapp/src/app/store/task/action.ts
- apps/tenant-management-webapp/src/app/store/task/api.tsx
- apps/tenant-management-webapp/src/app/store/task/model.ts
- apps/tenant-management-webapp/src/app/store/task/reducers.ts
- apps/tenant-management-webapp/src/app/store/task/sagas.ts
> CS-2350 task queue list

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
> fix width of name so tables are aligned

- apps/tenant-management-webapp/src/app/pages/admin/services/task/queueTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/task/queueTableItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/task/queuesList.tsx
- apps/tenant-management-webapp/src/app/store/task/action.ts
- apps/tenant-management-webapp/src/app/store/task/api.tsx
- apps/tenant-management-webapp/src/app/store/task/model.ts
- apps/tenant-management-webapp/src/app/store/task/reducers.ts
- apps/tenant-management-webapp/src/app/store/task/sagas.ts
> CS-1750 - Delete button

- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/subscription/subscriptionList.tsx
> CS-2398 - Accessiblity - Subscriptions Page

- apps/tenant-management-webapp/src/app/pages/admin/services/task/queuesList.tsx
- apps/tenant-management-webapp/src/app/store/config/models.ts
- apps/tenant-management-webapp/src/app/store/task/action.ts
- apps/tenant-management-webapp/src/app/store/task/api.tsx
- apps/tenant-management-webapp/src/app/store/task/model.ts
- apps/tenant-management-webapp/src/app/store/task/reducers.ts
- apps/tenant-management-webapp/src/app/store/task/sagas.ts
> CS-1750 - delete fix / not saved in correct place

- apps/tenant-management-webapp/src/app/pages/admin/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/comment.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/routers.tsx
- apps/tenant-management-webapp/src/app/store/config/models.ts
- apps/tenant-management-webapp/src/featureFlag.ts
> CS-2399 - Comment Tab

- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/previewEditor/TemplateEditor.tsx
- apps/tenant-management-webapp/src/app/store/sharedSelectors/roles.ts
- apps/tenant-management-webapp/src/app/store/stream/selectors.ts
- apps/tenant-management-webapp/src/app/store/task/sagas.ts
> fix linting

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/formDefinitionItem.tsx
- apps/tenant-management-webapp/src/app/store/form/sagas.ts
Also if there is no description not having a ? would occasionally cause an error
> must have accidentally renamed the delete form to delete comment

- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/subscription/subscriptionList.tsx
I had accidentally removed this one
> missed one

- apps/tenant-management-webapp/src/app/pages/admin/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/commentTopicTypesEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/topicTypes.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitions.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/formDefinitionEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/pdfTemplateEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/pdf/templates/templates.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/styled-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/task/TaskDefinationEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/task/queuesList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/task/styled-components.ts
sidebar itself creates scrolling - don't need these if you manage scrollbar
> Cs 2444 - sidebar itself creates scrolling - don't need these if you manage scrollbar

- apps/push-service/src/main.ts
- apps/push-service/src/push/events.ts
- apps/push-service/src/push/router/stream.ts
Also removing user info from webhook event since webhook is triggered by events without a specific user context and removing extraneous tenants request.
> fix(push-service): add core strategy on endpoints.

- apps/subscriber-app/src/app/notificationBanner.tsx
- apps/subscriber-app/src/app/store/config/sagas.ts
- apps/subscriber-app/src/app/store/notification/sagas.ts
- apps/subscriber-app/src/app/store/notifications/models.ts
- apps/subscriber-app/src/app/store/notifications/reducers.ts
- apps/subscriber-app/src/app/store/subscription/sagas.ts
- apps/subscriber-app/src/app/store/tenant/sagas.ts
- apps/tenant-management-webapp/src/app/notificationBanner.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendarModal.tsx
- apps/tenant-management-webapp/src/app/store/access/sagas.ts
- apps/tenant-management-webapp/src/app/store/calendar/sagas.ts
- apps/tenant-management-webapp/src/app/store/comment/sagas.ts
- apps/tenant-management-webapp/src/app/store/configuration/sagas.ts
- apps/tenant-management-webapp/src/app/store/directory/sagas.ts
- apps/tenant-management-webapp/src/app/store/event/sagas.ts
- apps/tenant-management-webapp/src/app/store/file/sagas.ts
- apps/tenant-management-webapp/src/app/store/form/sagas.ts
- apps/tenant-management-webapp/src/app/store/index.ts
- apps/tenant-management-webapp/src/app/store/metrics/sagas.ts
- apps/tenant-management-webapp/src/app/store/notice/sagas.ts
- apps/tenant-management-webapp/src/app/store/notification/sagas.ts
- apps/tenant-management-webapp/src/app/store/notifications/models.ts
- apps/tenant-management-webapp/src/app/store/notifications/reducers.ts
- apps/tenant-management-webapp/src/app/store/pdf/sagas.ts
- apps/tenant-management-webapp/src/app/store/script/sagas.ts
- apps/tenant-management-webapp/src/app/store/status/sagas.ts
- apps/tenant-management-webapp/src/app/store/stream/saga.ts
- apps/tenant-management-webapp/src/app/store/subscription/sagas.ts
- apps/tenant-management-webapp/src/app/store/task/sagas.ts
- apps/tenant-management-webapp/src/app/store/tenant/sagas.ts
> CS-2447 - Tenant Management Webapp

- apps/comment-service/src/comment/configuration.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/addEditCommentTopicTypeEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/commentTopicTypesItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/definitionsList.tsx
- apps/tenant-management-webapp/src/app/store/comment/model.ts
> CS-2448 - Data Classification on Topic Types

- apps/tenant-management-webapp/src/app/components/Html.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/eventList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/eventListFilter.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/styled-components.ts
- apps/tenant-management-webapp/src/app/store/calendar/models.ts
> feat: update the calenar event filter based on the new design

- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/addEditCommentTopicTypeEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/commentTopicTypesItem.tsx
> capitalize Protection type, but only visually

- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/addEditCommentTopicTypeEditor.tsx
> change requested by Zion

- apps/tenant-management-webapp/src/app/pages/admin/services/file/addEditFileTypeDefinitionEditor.tsx
Fix for call out not appearing when dropdown selection is made.
> Fix for callout warning not showing

- apps/tenant-management-webapp/src/featureFlag.ts
I need this approved but I need to wait to merge until i've update the backend
> CS-2493-2494 by default - turn off Task and Comment

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/eventList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/styled-components.ts
> Update the calendar event UI

- apps/tenant-management-webapp/src/featureFlag.ts
Previous logic only would have worked if all the flags were set explicitly in ConfigMag
> Cs 2493 2494 Fix feature flags

- apps/tenant-management-webapp/src/app/components/RoleTable.tsx
- apps/tenant-management-webapp/src/app/lib/validation/checkInput.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/addEditCommentTopicTypeEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/commentTopicTypesItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/task/queueModalEditor.tsx
- apps/tenant-management-webapp/src/app/store/comment/model.ts
> CS-2528 / some uppercase-lowercase fixes

- apps/tenant-management-webapp/src/app/pages/admin/services/file/addEditFileTypeDefinitionEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypesTable.tsx
> Title case security classification labels

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/eventList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/eventListFilter.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/styled-components.ts
- apps/tenant-management-webapp/src/app/store/calendar/actions.ts
- apps/tenant-management-webapp/src/app/store/calendar/models.ts
- apps/tenant-management-webapp/src/app/store/calendar/sagas.ts
> Update the calendar event  based on v3 of the design

- apps/file-service/src/file/events.ts
- apps/file-service/src/file/model/file.spec.ts
- apps/file-service/src/file/model/file.ts
- apps/file-service/src/file/router/file.spec.ts
- apps/file-service/src/file/router/file.swagger.yml
- apps/file-service/src/file/router/file.ts
- apps/file-service/src/file/router/upload.ts
- apps/file-service/src/file/storage.ts
- apps/file-service/src/file/types/file.ts
- apps/file-service/src/mongo/file.ts
- apps/file-service/src/storage/azure-blob.ts
- apps/file-service/src/storage/file-system.ts
This PR is to add the security classification property into the file when it is being created or updated.
> Security Classification for file endpoints

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitionsList.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/form.tsx
> CS-2505 - Definition consistency

- apps/notification-service/src/notification/router/subscription.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/commentTopicTypesItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/subscribers/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/subscribers/subscriberListItem.tsx
- libs/adsp-service-sdk/src/access/user.ts
* When a user subscriber (i.e. subscriber associated with current user) is created, the email channel verified status is set based on email_verified in the access token handled in subscriber creation endpoint, and in subscription creation endpoint.
* default to false if claim is not present in token
* In tenant admin, the Notification service → Subscribers list indicates if emails and/or sms address is verified. see screenshot
verified status is set when the subscriber is created, and not synchronized afterwards (i.e. must be deleted and recreated to sync if account is changed)
> CS-2534 - Add an authenticated user

- apps/subscriber-app/src/app/pages/private/Subscriptions/ContactInfoCard.tsx
- apps/subscriber-app/src/app/pages/private/Subscriptions/styled-components.ts
> Add the email verification to subscription app

- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/subscribers/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/subscribers/subscriberListItem.tsx
- apps/tenant-management-webapp/src/app/store/notifications/models.ts
> use badged instead

- apps/subscriber-app/src/app/pages/private/Subscriptions/ContactInfoCard.tsx
- apps/subscriber-app/src/app/pages/private/Subscriptions/styled-components.ts
- apps/subscriber-app/src/main.tsx
> Update the subscriber app UI

- apps/file-service/src/file/router/file.swagger.yml
Update file service swagger api for security classification.
> update file service swagger api

- apps/push-service/src/main.ts
- apps/push-service/src/push/model/stream.spec.ts
- apps/push-service/src/push/model/stream.ts
- apps/push-service/src/push/router/stream.spec.ts
Adding logging for diagnostics of if push notifications are being sent.
> chore(push-service): adding logging of push service stream filtering

- libs/adsp-service-sdk/src/configuration/configurationUpdateHandler.ts
Change to handle update stream reconnect explicitly instead of using auto reconnect and force websocket transport.
> fix(adsp-service-sdk): handle configuration update stream reconnect

- apps/tenant-management-webapp-e2e/src/integration/task.feature
Added a new e2e test for task overview page
> CS-2589 - e2e test for task overview page

- apps/status-service/src/mongo/schema.ts
Current pattern props overlaps with known props (e.g. contact) and causes validation failure.
> fix(status-service): moving application schema to additional props

- apps/tenant-management-webapp/src/app/pages/admin/services/access/serviceRoles/serviceRoles.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendar/calendarsView.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/addEditCommentTopicTypeEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/events/stream/index.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypes.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/form.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/notificationTypes.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/script/scriptsView.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/task/queueModalEditor.tsx
- apps/tenant-management-webapp/src/app/privateApp.tsx
- apps/tenant-management-webapp/src/app/store/access/actions.ts
- apps/tenant-management-webapp/src/app/store/access/sagas.ts
- apps/tenant-management-webapp/src/app/store/tenant/sagas.ts
> Revert the service role fetch: now lazy loading the service roles

- apps/tenant-management-webapp/src/app/pages/admin/services/file/addEditFileTypeDefinitionEditor.tsx
Removing unnecessary fetches for files to the server on load for the file type editor
> Removing unnecessary fetches for files on load

- apps/notification-service/src/assets/verify-email-template.hbs
- apps/notification-service/src/assets/verify-sms-template.hbs
- apps/notification-service/src/notification/model/subscriber.spec.ts
- apps/notification-service/src/notification/model/subscriber.ts
- apps/notification-service/src/notification/router/subscription.spec.ts
- apps/notification-service/src/notification/router/subscription.ts
- apps/notification-service/src/notification/router/types.ts
- apps/notification-service/src/notification/verify.ts
- apps/notification-service/src/verify.ts
- apps/subscriber-app/src/app/pages/private/Subscriptions/ContactInfoCard.tsx
- apps/subscriber-app/src/app/pages/private/Subscriptions/SmsRedirect.tsx
- apps/subscriber-app/src/app/pages/private/Subscriptions/Subscriptions.tsx
- apps/subscriber-app/src/app/pages/private/Subscriptions/styled-components.ts
- apps/subscriber-app/src/app/pages/public/Subscriptions.tsx
- apps/subscriber-app/src/app/pages/validateModal.tsx
- apps/subscriber-app/src/app/privateApp.tsx
- apps/subscriber-app/src/app/store/subscription/actions.ts
- apps/subscriber-app/src/app/store/subscription/models.ts
- apps/subscriber-app/src/app/store/subscription/reducers.ts
- apps/subscriber-app/src/app/store/subscription/sagas.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topicTypes/addEditCommentTopicTypeEditor.tsx
* Clean up ui and create a separate verify channel modal
* Fix phone flow
should fix CS-2613 as well
> CS-2544 - Verify Channel Modal

- libs/adsp-service-sdk/src/configuration/configurationUpdateHandler.ts
- libs/adsp-service-sdk/src/metrics/handler.ts
Also updating metrics handler to check user for tenant context in case tenant handler is not included on route.
> chore(adsp-service-sdk): change SDK to use socket auth

- apps/token-handler/src/token/model/client.spec.ts
- apps/token-handler/src/token/model/client.ts
- apps/token-handler/src/token/router/client.spec.ts
- apps/token-handler/src/token/router/client.ts
- apps/token-handler/src/token/router/session.spec.ts
- apps/token-handler/src/token/router/session.ts
- apps/token-handler/src/token/router/target.spec.ts
- apps/token-handler/src/token/router/target.ts
Also adding express validators to routes.
> chore(token-handler): adding router unit test coverage

- apps/tenant-management-api/src/tenant/router/tenant.swagger.yml
- docs/services/comment-service.md
Also making correction to comment service pages docs.
> fix(tenant-management-api): correct the response body schema in API docs

- apps/script-service/Events/ScriptEvent.cs
- apps/script-service/Events/ScriptExecuted.cs
- apps/script-service/Events/ScriptExecutionFailed.cs
> fix: inline code script service schemas

- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topics/topicTableItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topics/topicsTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
Ensuring the default template doesn't have accessiblity errors
> CS-2675 remove accessiblity issues by default

- .openshift/configuration/task-app.yml
- apps/task-app/proxy.conf.json
- apps/task-app/src/app/containers/FeedbackNotification.tsx
- apps/task-app/src/app/containers/TaskQueue.module.css
- apps/task-app/src/app/containers/TaskQueue.tsx
- apps/task-app/src/app/containers/TaskTenant.tsx
- apps/task-app/src/app/state/task.slice.ts
Also fixing configuration json format and adjusting task list components.
> chore(task-app): adding proxy for task app

- apps/task-app/src/app/state/task.slice.ts
- apps/task-app/src/app/state/user.slice.ts
Also correct the usage of isRejectedWithValue matcher.
> fix(task-app): handle error in socket auth

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinition.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
> remove generate button from main form template

- apps/form-service/src/form/events.ts
- apps/form-service/src/form/index.ts
- apps/form-service/src/form/model/form.spec.ts
- apps/form-service/src/form/model/form.ts
- apps/form-service/src/form/model/formSubmission.ts
- apps/form-service/src/form/model/index.ts
- apps/form-service/src/form/notifications.ts
- apps/form-service/src/form/repository/formSubmission.ts
- apps/form-service/src/form/repository/index.ts
- apps/form-service/src/form/router/form.spec.ts
- apps/form-service/src/form/router/form.ts
- apps/form-service/src/form/router/types.ts
- apps/form-service/src/form/types/form.ts
- apps/form-service/src/mongo/formSubmission.ts
- apps/form-service/src/mongo/index.ts
- apps/form-service/src/mongo/schema.ts
- apps/form-service/src/mongo/types.ts
CS-2468 - Add form submission - 
Allow multiple forms to be created based on CS-2452 
fulfills CS-2468 requirement - 
`Form service form submit operation uses configuration to create submission records if appropriate.`
> CS-2468 - Add form submission database

- apps/comment-service/migrations/20240105003328_nullable_title.js
- apps/comment-service/migrations/20240105153554_change_content_type.js
- apps/comment-service/src/comment/router/topic.swagger.yml
- apps/comment-service/src/comment/router/topic.ts
- apps/comment-service/src/comment/types/comment.ts
Also updating column types so content length is unlimited.
> fix(comment-service): making comment title optional

- apps/comment-service/src/comment/router/topic.ts
- apps/task-app/src/app/components/TaskHeader.tsx
- apps/task-app/src/app/containers/CommentsViewer.tsx
- apps/task-app/src/app/containers/TaskQueue.tsx
- apps/task-app/src/app/containers/details/TaskDetailsHost.tsx
- apps/task-app/src/app/state/comment.slice.ts
- apps/task-app/src/app/state/index.ts
- apps/task-app/src/app/state/store.ts
- apps/task-app/src/app/state/task.slice.ts
- apps/task-app/src/app/state/types.ts
- apps/task-app/src/main.tsx
Also allowing nulls on express validators in comment service create comment endpoint.
> feat(task-app): adding comment pane to task details view

- apps/task-service/src/comment.ts
- apps/task-service/src/main.ts
Also improving error handling in comment service client to log payload from axios error when available.
> fix(task-service): fix comment configuration type key

- libs/jsonforms-components/src/index.ts
- libs/jsonforms-components/src/lib/Controls/Inputs/InputTextControl.tsx
- libs/jsonforms-components/src/lib/Controls/ObjectArray/DeleteDialog.tsx
- libs/jsonforms-components/src/lib/Controls/ObjectArray/ObjectArray.tsx
- libs/jsonforms-components/src/lib/Controls/ObjectArray/ObjectArrayToolBar.tsx
- libs/jsonforms-components/src/lib/Controls/ObjectArray/ObjectListControl.tsx
- libs/jsonforms-components/src/lib/Controls/ObjectArray/index.tsx
- libs/jsonforms-components/src/lib/Controls/ObjectArray/styled-components.tsx
- libs/jsonforms-components/src/lib/Controls/index.tsx
> Add the object array control

- apps/task-app/src/app/containers/TaskQueue.tsx
- apps/task-app/src/app/containers/details/TaskDetailsHost.tsx
- apps/task-app/src/app/state/feedback.slice.ts
- apps/task-app/src/app/state/task.slice.ts
- apps/task-app/src/app/state/user.slice.ts
This results in a request without a token and a 401 result which is handled with a reducer. Also adding a load task action to support deep linking to a specific task.
> fix(task-app): handle updateToken err by returning null token

- apps/tenant-management-webapp/src/app/pages/admin/services/task/queuesList.tsx
> CS-2726 - Sort queues by both Namespace and Name

- libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperControl.tsx
currently multi-step form is broken if no data exists
> fix error in multi-step form

- apps/task-app/src/app/app.spec.tsx
- apps/task-app/src/app/components/QueueListItem.tsx
- apps/task-app/src/app/state/queue.slice.ts
- apps/task-app/src/app/state/task.slice.ts
- apps/task-app/src/app/state/types.ts
Also add sort of queues by display name, namespace, then name.
> fix(task-app): correct name of socket disconnect event

- apps/form-app/src/app/state/file.slice.ts
- apps/task-app/src/app/state/file.slice.ts
- apps/task-app/src/app/state/user.slice.ts
Also adding some error handling in task app file state slice.
> feat(form-app): adding file upload and delete in state slice

- apps/form-app/src/app/components/StartApplication.tsx
- apps/form-app/src/app/containers/Form.tsx
- apps/form-app/src/app/containers/FormDefinition.tsx
- apps/form-app/src/app/state/form.slice.ts
- apps/form-app/src/app/state/util.ts
- apps/form-app/src/environments/environment.ts
Also adjusting behaviours around resolving existing draft for the user.
> feat(task-app): adjusting save behaviour to avoid extraneous saves

- apps/comment-service/src/comment/model/topic.ts
- apps/comment-service/src/comment/model/type.ts
- apps/form-service/src/comment.ts
- apps/form-service/src/form/comment.ts
- apps/form-service/src/form/configuration.ts
- apps/form-service/src/form/index.ts
- apps/form-service/src/form/jobs/delete.spec.ts
- apps/form-service/src/form/jobs/lock.spec.ts
- apps/form-service/src/form/model/definition.spec.ts
- apps/form-service/src/form/model/definition.ts
- apps/form-service/src/form/model/form.spec.ts
- apps/form-service/src/form/roles.ts
- apps/form-service/src/form/router/form.spec.ts
- apps/form-service/src/form/router/form.ts
- apps/form-service/src/form/types/definition.ts
- apps/form-service/src/main.ts
Also adjust comment service to allow topic specific commenters to read.
> feat(form-service): create form support topic

- apps/form-app/src/app/containers/Form.tsx
- apps/form-app/src/app/containers/FormTenant.tsx
- apps/form-app/src/app/state/user.slice.ts
- apps/task-app/src/app/state/user.slice.ts
Also adding a comment regarding login behaviour for development clarity.
> feat(form-app): adjust some elements for mobile screen sizes

- apps/script-service/Events/ScriptSubscriber.cs
For event triggered scripts, a script run failure should be handled via error handling within the script instead of by the event consumer.
> fix(script-service): catch and log script run error in subscriber

- apps/token-handler/src/token/csrf.ts
Support file API resources as image src with credentials.
> feat(token-handler): exclude GET from csrf check

- libs/jsonforms-components/src/index.ts
- libs/jsonforms-components/src/lib/layouts/GroupControl.tsx
- libs/jsonforms-components/src/lib/layouts/index.ts
> feat:  Add Group layout control to Jsonforms implementation

- libs/jsonforms-components/src/lib/Controls/FileUploader/FileUploaderControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputBaseControl.tsx
A) Get rid of a bunch of errors in the console
B) Fix error validation problem related to dropdowns
> CS-2750 Form bug fixes

- apps/tenant-management-api/src/environments/environment.ts
- apps/tenant-management-api/src/main.ts
Reverts GovAlta/adsp-monorepo#2586
> Revert "Add the internal keycloak host for create tenant service"

- apps/form-app/src/app/components/DraftForm.tsx
- apps/form-app/src/app/components/SubmittedForm.tsx
- apps/form-app/src/app/containers/Form.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
- libs/jsonforms-components/README.md
- libs/jsonforms-components/src/index.ts
- libs/jsonforms-components/src/lib/Context/index.tsx
- libs/jsonforms-components/src/lib/Controls/FileUploader/FileUploaderControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputBaseControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputEnum.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputEnumAutoComplete.tsx
* Dropping both classes I added to modules
* Simplify <JsonForms />
* use <ContextProvider and put <JsonFormContext.Provider value inside module
> CS-2750 - drop classes in module

- apps/pdf-service/jest.config.ts
- apps/pdf-service/src/file.spec.ts
- apps/pdf-service/src/pdf/job/generate.spec.ts
- apps/pdf-service/src/puppeteer.spec.ts
- apps/pdf-service/src/puppeteer.ts
Also mocking puppeteer in unit tests for more consistent unit test execution.
> chore(pdf-service): enabling coverage

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinition.tsx
- apps/tenant-management-webapp/src/app/store/directory/selectors.ts
- apps/tenant-management-webapp/src/app/store/form/model.ts
- apps/tenant-management-webapp/src/app/store/form/selectors.ts
Add the formDraftUrlTemplate to the json form definition
> Add the formDraftUrlTemplate to the json form definition

- apps/task-app/src/app/containers/AuthorizeUser.tsx
Error on login (typically due to user not having tokens) previously caused infinite loop - this fixes is -
> CS-2508 - prevent infinite loop if user doesn't have correct tokens

- libs/jsonforms-components/src/lib/Controls/Inputs/InputDateTimeControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputTimeControl.tsx
DateTime and Time controls triggering error messages when a value is set.
> Fix: DateTime and Time controls triggering error messages 

- apps/form-service/src/form/model/form.ts
- apps/form-service/src/notification.spec.ts
- apps/form-service/src/notification.ts
Cache subscribers to reduce how often form service needs to make request to notification service API.
> chore(form-service): add caching of subscribers

- apps/script-service/Services/IScriptFunctions.cs
- apps/script-service/Services/Platform/DispositionResponse.cs
- apps/script-service/Services/ScriptFunctions.cs
- apps/script-service/Services/StubScriptFunctions.cs
- apps/tenant-management-webapp/src/app/lib/luaCodeCompletion.ts
> CS-2865 -  Disposition of form submission from script

- libs/jsonforms-components/.releaserc.json
- libs/jsonforms-components/project.json
Adding the release target for publishing the jsonforms-components library.
> chore(jsonforms-components): adding release target project

- libs/jsonforms-components/src/lib/Controls/Inputs/InputDateControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputDateTimeControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputIntegerControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputMultiLineTextControl.spec.ts
- libs/jsonforms-components/src/lib/Controls/Inputs/InputMultiLineTextControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputNumberControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputTextControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputTimeControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/inputControl.spec.ts
- libs/jsonforms-components/src/lib/Controls/Inputs/type.ts
- libs/jsonforms-components/src/lib/util/inputControlUtils.ts
Also added readOnly property for input controls that has this property in it.
> fix(jsonforms-components): refactor input event handling and add unit tests

- .github/actions/nx-cypress-e2e/action.yml
- .github/workflows/artillery.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/delivery-ci.yml
- .github/workflows/e2e.yml
- .github/workflows/nightly.yml
- .github/workflows/promote.yml
- .github/workflows/pull-request.yml
Updating actions for github actions node 16 runtime end of support.
> chore: updating version of actions

- apps/form-app/src/app/components/SubmittedForm.tsx
- apps/form-app/src/app/state/form.slice.ts
Also reducing save debounce time so save appears more responsive.
> chore(form-app): adjusting submitted form spacing

- apps/file-service/src/file/model/file.spec.ts
- apps/file-service/src/file/model/file.ts
- apps/file-service/src/file/router/file.spec.ts
- apps/file-service/src/file/router/file.swagger.yml
- apps/file-service/src/file/router/file.ts
- apps/file-service/src/file/router/upload.spec.ts
- apps/file-service/src/file/storage.ts
- apps/file-service/src/storage/azure-blob.ts
- apps/file-service/src/storage/file-system.ts
Copy operation makes a copy of the file within the storage provider.
> feat(file-service): support copy via a file operation endpoint

- .github/actions/nx-cypress-e2e/action.yml
Also including environment in artifact name to avoid collision in pipeline run.
> chore: update cypress action for node 16 action deprecation

- apps/tenant-management-webapp/src/app/pages/admin/services/access/TenantIDP.tsx
- apps/tenant-management-webapp/src/app/store/tenant/sagas.ts
> feat: ui touchup for the troubleshooting

- apps/subscriber-app-e2e/src/integration/subscription-management.feature
- apps/subscriber-app-e2e/src/integration/subscription-management/subscription-management.step.ts
- apps/tenant-management-webapp-e2e/src/integration/tenant-admin.feature
- apps/tenant-management-webapp-e2e/src/integration/tenant-admin/tenant-admin.step.ts
e2e - Automated test for login apps with tenant name for tenant management and subscriber app
> e2e - Automated test login apps with tenant name

- libs/adsp-feedback/src/main.ts
- libs/adsp-feedback/src/types.d.ts
- libs/adsp-feedback/tsconfig.lib.json
Also moving type definitions in declaration file as reference.
> chore(adsp-feedback): adjusting styles

- apps/form-app/src/app/components/DraftForm.tsx
- apps/form-app/src/app/state/file.slice.ts
- apps/form-app/src/app/state/form.slice.ts
- libs/core-common/src/jsonSchema/ajv.ts
- libs/jsonforms-components/src/lib/Controls/FileUploader/FileUploaderControl.tsx
- libs/jsonforms-components/src/lib/common/Ajv.ts
- Modifications to Redux and how the file data is mapped so that we can use it in the FileUploadControl using JsonForms Context.
- Added Redux Action to update the form files in the in the Redux store.
- Modify Ajv file-urn format pattern for the file urn.
> fix(form-app):  upload file control for uploading and deleting a file.

- apps/feedback-service/src/feedback/configuration.ts
- apps/pii-service/pii_service/app.py
Include analyzer role in tenant admin, and allow more characters in site url.
> chore(pii-service, feedback-service): some adjustments to configuration

- apps/status-service/src/mongo/notice.spec.ts
- apps/status-service/src/mongo/notice.ts
> fix(active notice) - notice api did not take active into account

- apps/feedback-service/src/main.ts
- apps/form-service/src/instrument.ts
- apps/form-service/src/main.ts
Also instrumenting axios in form service for request timing information.
> chore(feedback-service, form-service): adjusting configuration cache TTL

- libs/adsp-feedback/src/main.ts
Use query param on the script element src for single script element inclusion of the widget.
> feat(adsp-feedback): support simple initialization via query param

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/JsonFormPreviewer.tsx
Reverts GovAlta/adsp-monorepo#2864
> Revert "fix(label change): Update preview on radio label change"

- apps/task-app/src/app/containers/details/FormSubmissionReviewTask.spec.tsx
- apps/task-app/src/app/containers/details/FormSubmissionReviewTask.tsx
- apps/task-app/src/app/containers/details/GenerateFormFields.ts
- apps/task-app/src/app/containers/details/RenderFormReviewFields.spec.tsx
- apps/task-app/src/app/containers/details/RenderFormReviewFields.tsx
- apps/task-app/src/app/containers/details/getRequiredFields.tsx
- apps/task-app/src/app/containers/details/styled-components.tsx
- apps/task-app/src/app/state/form.slice.ts
- apps/task-app/src/app/state/index.ts
- apps/task-app/src/app/state/store.ts
- apps/task-app/src/app/state/task.slice.ts
- apps/task-app/src/app/state/types.ts
- apps/task-app/src/lib/adspId.ts
- apps/task-app/src/lib/common/Grid.tsx
- apps/task-app/src/lib/validations/checkInput.ts
- libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperControl.tsx
> feature(task from submission view): shows data entered and files

- apps/tenant-management-webapp/src/app/lib/handlebarHelper.ts
> fix: set empty string to notification template

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/categorization.ts
- libs/jsonforms-components/src/lib/Additional/HelpContent.tsx
- libs/jsonforms-components/src/lib/Additional/LinkControl.tsx
> fix(form-link): change name to hyperlink and add icon

- libs/adsp-feedback/src/main.ts
> fix(feedback mobile): put feedback on the bottom of the viewport

- apps/tenant-management-webapp-e2e/src/integration/notifications.feature
- apps/tenant-management-webapp-e2e/src/integration/service-status.feature
e2e - test updates to use GoA test account emails
> e2e - test updates to use GoA test account emails

- apps/form-service/src/form/model/form.ts
- apps/form-service/src/form/types/form.ts
- apps/form-service/src/mongo/form.ts
- apps/form-service/src/mongo/schema.ts
- apps/tenant-management-webapp-e2e/src/integration/form/form.page.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.spec.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/infoCircleWithInlineHelp.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/styled-components.ts
- apps/tenant-management-webapp/src/app/store/form/model.ts
> feature(support topic): Configure support topic

- apps/configuration-service/src/configuration/configuration.ts
- apps/configuration-service/src/configuration/repository/configuration.ts
- apps/configuration-service/src/configuration/router/configuration.ts
- apps/configuration-service/src/mongo/repository.ts
- apps/tenant-management-webapp/src/app/lib/kebabName.ts
- apps/tenant-management-webapp/src/app/store/form/api.tsx
- apps/tenant-management-webapp/src/app/store/form/model.ts
- apps/tenant-management-webapp/src/app/store/form/sagas.ts
Save to form-service namespace as well as the platform:form-service configuration for transition to namespace based configuration.
> feat(tenant-management-webapp): save form definition in config namespace

- apps/tenant-management-webapp-e2e/src/integration/configuration-service.feature
e2e - set core configuration test to be smoke test
> e2e - set core configuration test to be smoke test

- apps/event-service/jest.config.ts
- apps/event-service/src/event/index.spec.ts
> fix(code-coverage): Up event service code coverage to 80%

- apps/pdf-service/src/pdf/job/generate.spec.ts
- apps/pdf-service/src/pdf/job/generate.ts
- apps/pdf-service/src/pdf/model/template.spec.ts
- apps/pdf-service/src/pdf/router/pdf.spec.ts
- apps/pdf-service/src/pdf/router/pdf.ts
- apps/pdf-service/src/submittedForm/template.ts
To use:
POST:   ----pdf-service---/pdf/v1/jobs
BODY:
```
{
"operation":"generate",
"templateId":"submitted-form",
"data":{
"content":{
"config":{
"id":"a10generated",
"name":"a10generated",
"description":"",
"dataSchema":{
"type":"object",
"properties":{
"firstName":{
"type":"string",
"minLength":4,
"description":"Please enter your first name",
"default":"abc"
},
"secondName":{
"type":"string",
"minLength":3,
"description":"Please enter your second name",
"default":"Weyermann"
},
"vegetarian":{
"type":"boolean"
},
"birthDate":{
"type":"string",
"format":"date",
"description":"Please enter your birth date."
},
"nationality":{
"type":"string",
"enum":[
"DE",
"IT",
"JP",
"US",
"RU",
"Other"
]
},
"provideAddress":{
"type":"boolean"
},
"address":{
"type":"object",
"properties":{
"street":{ …
```
> fix(pdf generation): all data now passed through api endpoint

- .openshift/managed/cache-service.yml
- .openshift/managed/form-service.yml
- apps/cache-service/src/main.ts
- apps/configuration-service/src/main.ts
- apps/file-service/src/main.ts
Also adding APIs to registered cache target configuration for configuration service and file service.
> chore(cache-service): add metrics and include directory overrides

- apps/pdf-service/src/handlebars.ts
> feat(equal comparisons): allow equal comparison on PDF generation

- .openshift/managed/cache-service.yml
- .openshift/managed/calendar-service.yml
- .openshift/managed/comment-service.yml
- .openshift/managed/feedback-service.yml
- .openshift/managed/file-service.yml
- .openshift/managed/notification-service.yml
- .openshift/managed/pdf-service.yml
- .openshift/managed/status-service.yml
- .openshift/managed/task-service.yml
- apps/pdf-service/src/pdf/router/pdf.spec.ts
- apps/pdf-service/src/pdf/router/pdf.ts
- apps/task-service/project.json
Also, removing some remnant code for formId in pdf service.
> chore: updating manifests for consistency

- apps/tenant-management-webapp/src/app/components/Tabs.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/PDFPreviewTemplateCore.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/styled-components.ts
- apps/tenant-management-webapp/src/app/store/form/model.ts
> fix(hide PDF preview): Create PDF on submit checked shows PDF preview

- apps/configuration-service/src/configuration/repository/configuration.ts
- apps/configuration-service/src/configuration/router/__snapshots__/configuration.spec.ts.snap
- apps/configuration-service/src/configuration/router/configuration.spec.ts
- apps/configuration-service/src/configuration/router/configuration.ts
- apps/configuration-service/src/mongo/repository.ts
- apps/directory-service/src/directory/router/resource.swagger.yml
Also removing extraneous _id property from namespace search endpoint, and correcting some endpoints in directory service api docs.
> feat(configuration-service): add urn to response

- apps/directory-service/src/directory/events.ts
- apps/directory-service/src/directory/index.ts
- apps/directory-service/src/main.ts
- apps/file-service/src/file/router/file.ts
- apps/file-service/src/file/types/user.ts
- apps/file-service/src/main.ts
Support resolving file resources in directory, so files can be tagged and searched by tag.
> feat(file-service): register directory configuration

- apps/directory-service/src/directory/job/index.ts
Ack events so consumer can pull next item from queue.
> fix(directory-service): ack events not matched to jobs

- apps/directory-service/src/directory/router/resource.swagger.yml
- apps/directory-service/src/directory/router/resource.ts
- apps/directory-service/src/directory/types/resource.ts
- apps/directory-service/src/mongo/repository.ts
- apps/directory-service/src/mongo/schema.ts
- apps/directory-service/src/mongo/types.ts
Also, naming collections explicitly when initializing models.
> fix(directory-service): apply index on correct collection

- apps/configuration-service/src/configuration/events.ts
- apps/configuration-service/src/configuration/router/configuration.spec.ts
- apps/configuration-service/src/configuration/router/configuration.ts
- apps/configuration-service/src/main.ts
- apps/directory-service/src/mongo/repository.ts
Register delete event for directory service management of resources. This allows configuration directory resources to be removed when configuration is deleted.
> feat(configuration-service): add delete event for resource lifecycle

- apps/configuration-service/src/configuration/repository/types.ts
- apps/configuration-service/src/main.ts
- apps/configuration-service/src/mongo/repository.ts
Also adding axios instrumentation for timings.
> feat(configuration-service): order configuration in pipeline

- apps/comment-service/project.json
- apps/comment-service/src/comment/events.spec.ts
- apps/comment-service/src/main.ts
Also adding unit tests for event schema validation.
> feat(comment-service): register topic resource

- apps/tenant-management-webapp-e2e/src/integration/common/common.steps.ts
- apps/tenant-management-webapp-e2e/src/integration/feedback.feature
- apps/tenant-management-webapp-e2e/src/integration/feedback/feedback.page.ts
- apps/tenant-management-webapp-e2e/src/integration/feedback/feedback.step.ts
> e2e - submit feedback test

- apps/form-service/src/form/index.ts
- apps/form-service/src/form/model/form.spec.ts
- apps/form-service/src/form/model/form.ts
- apps/form-service/src/form/pdf.ts
- apps/form-service/src/form/router/form.spec.ts
- apps/form-service/src/form/router/form.swagger.yml
- apps/form-service/src/form/router/form.ts
- apps/form-service/src/main.ts
- apps/form-service/src/pdf.spec.ts
- apps/form-service/src/pdf.ts
Also encapsulate PDF generation for better testability.
> feat(form-service): support update data and submit in create

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/JsonFormPreviewer.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
- apps/tenant-management-webapp/src/app/store/configuration/action.ts
- apps/tenant-management-webapp/src/app/store/configuration/model.ts
- apps/tenant-management-webapp/src/app/store/configuration/reducers.ts
- apps/tenant-management-webapp/src/app/store/configuration/sagas.ts
- libs/jsonforms-components/src/lib/Context/register/actions.ts
- libs/jsonforms-components/src/lib/Context/register/reducer.ts
- libs/jsonforms-components/src/lib/Context/register/register.spec.tsx
- libs/jsonforms-components/src/lib/Context/register/registerContext.tsx
- libs/jsonforms-components/src/lib/Context/register/util.ts
- libs/jsonforms-components/src/lib/Controls/Inputs/InputEnum.spec.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputEnum.tsx
> feature(register request errors): show inline warnings

- apps/value-service/src/values/router/value.swagger.yml
> fix(swagger fix) - represents the actual feature of names

- apps/form-app/src/app/app.module.scss
- apps/form-app/src/app/containers/Form.tsx
> fix(feedback sidebar): prevent scrollbar from being on top

- apps/tenant-management-webapp/src/app/pages/admin/services/status/notices/noticeCard.tsx
> fix(gear icon) - replace gear icon

- apps/value-service/src/values/router/value.ts
> fix(value names): 404 if names do not exist

- apps/form-service/src/form/pdf.ts
- apps/pdf-service/src/handlebars.ts
- apps/pdf-service/src/pdf/partials/elements.hbs
> fix(listWithDetails): now displays correctly in the PDF

- apps/tenant-management-webapp/babel-jest.config.json
- apps/tenant-management-webapp/src/app/lib/autoComplete/form.ts
Provide contextual completion based on scope property definition, and determine if completion is inserted into end or middle of peers.
> feat(tenant-management-webapp): improve UI schema completion

- apps/pdf-service/src/pdf/job/generate.ts
Ting
[Tuesday at 11:36 AM](https://goa-dio.slack.com/archives/C04UTA6QHTL/p1725989775079379?thread_ts=1725984591.755269&cid=C04UTA6QHTL)
[@Roy Styan](https://goa-dio.slack.com/team/U03A0KEUZEE)
, could you log the bug? the pdf generation should include extension when uploading the output pdf
> fix(CS-3525) - Forcing file extension to be PDF on generation

- libs/jsonforms-components/src/lib/Controls/Inputs/InputEnum.tsx
> fix(inline form error for dropdown): use callout instead

- apps/subscriber-gateway/src/subscriber/router.ts
Reverts GovAlta/adsp-monorepo#3431
> Revert "fix: update the correlation id in the status gateway"

- apps/tenant-management-webapp/src/app/lib/autoComplete/form.ts
- apps/tenant-management-webapp/src/app/lib/autoComplete/json.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinitionEditor.tsx
- libs/data-exchange-standard/src/common.v1.schema.json
Also adding sin common schema definition.
> feat(tenant-management-webapp): add completion items for data schema ref

- apps/status-service/src/app/events.spec.ts
- apps/status-service/src/app/events.ts
- apps/subscriber-gateway/src/subscriber/router.ts
Reverts GovAlta/adsp-monorepo#3435
> Revert "fix: update the correlation id used in the status events"

- apps/configuration-service/src/mongo/index.ts
- apps/configuration-service/src/mongo/repository.ts
Documentation seems to be incorrect and autoIndex not defaulting to true.
> chore(configuration-service): setting autoIndex to true

- apps/form-service/src/form/pdf.ts
- apps/pdf-service/src/handlebars.ts
- apps/pdf-service/src/pdf/partials/elements.hbs
> fix(Form PDF Generator) - Show array object

- apps/notification-service/src/notification/model/type.ts
> fix(Direct Notification): now uses sender email

- apps/notification-service/src/notification/model/type.ts
> fix(Direct Notifications) - Fixed Title and Subtitle

- apps/calendar-service/migrations/20240923161246_add_event_record_id.js
- apps/calendar-service/project.json
There appears to be some syntax difference between using chained schema changes.
> fix(calendar-service): change knex migration

- apps/calendar-service/src/calendar/model/event.ts
- apps/calendar-service/src/calendar/router/calendar.swagger.yml
- apps/calendar-service/src/calendar/router/calendar.ts
- apps/calendar-service/src/calendar/types/event.ts
- apps/calendar-service/src/postgres/calendar.ts
Also removing redundant startsAfter and endsBefore code in repository implementation.
> feat(calendar-service): add criteria for active events

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/import/import.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/file/uploadedFiles/fileList.tsx
> ref: replace current file uploader with design system uploader CS-3514

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/export/ServiceConfiguration.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/export/export.tsx
- apps/tenant-management-webapp/src/app/store/configuration/model.ts
- apps/tenant-management-webapp/src/app/store/configuration/sagas.ts
> feat(export/import configuration) : support namespace configurations

- apps/calendar-service/src/postgres/calendar.ts
- apps/form-service/src/calendar.spec.ts
- apps/form-service/src/calendar.ts
- apps/form-service/src/comment.spec.ts
- apps/form-service/src/comment.ts
- apps/form-service/src/form/calendar.ts
- apps/form-service/src/form/comment.ts
- apps/form-service/src/form/configuration.ts
- apps/form-service/src/form/index.ts
- apps/form-service/src/form/mapper.ts
- apps/form-service/src/form/model/definition.ts
- apps/form-service/src/form/roles.ts
- apps/form-service/src/form/router/form.spec.ts
- apps/form-service/src/form/router/form.ts
- apps/form-service/src/form/types/definition.ts
- apps/form-service/src/form/types/index.ts
- apps/form-service/src/form/types/intake.ts
- apps/form-service/src/main.ts
Initial implementation with read of intake information from calendar service.
> feat(form-service): add form-intake calendar

- .openshift/managed/file-service.yml
- apps/file-service/src/file/job/index.ts
- apps/file-service/src/main.ts
- apps/pdf-service/src/file.spec.ts
- apps/pdf-service/src/file.ts
Also allow file job pod to perform queue work in addition to scheduled jobs.
> chore(file-service): change av and job to deployments

- .openshift/managed/notification-service.yml
- apps/notification-service/project.json
- apps/notification-service/src/environments/environment.ts
- apps/notification-service/src/main.ts
- apps/notification-service/src/mongo/subscription.ts
- apps/notification-service/src/notification/router/subscription.ts
Adding dedicated deployment for jobs with consumer priority.
> fix(notification-service): adjusting use of $or operator

- apps/tenant-management-webapp/src/app/pages/admin/services/configuration/import/import.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/file/uploadedFiles/fileList.tsx
Reverts GovAlta/adsp-monorepo#3489
> Revert "ref: replace current file uploader with design system uploader CS-3514"

- apps/cache-service/src/cache/model/cacheTarget.spec.ts
- apps/cache-service/src/cache/model/cacheTarget.ts
Fallback to reading through to upstream if there is an error encountered during the cache read.
> fix(cache-service): handle error on cache retrieval

- .openshift/managed/cache-service.yml
- apps/cache-service/src/cache/model/cacheTarget.ts
- apps/cache-service/src/main.ts
- apps/cache-service/src/redis.spec.ts
- apps/cache-service/src/redis.ts
- apps/form-gateway/src/main.ts
- apps/pdf-service/src/main.ts
- apps/pdf-service/src/redis.ts
- apps/status-service/src/main.ts
- apps/token-handler/src/main.ts
Also, supporting TTL of 0 for cache service with persistent cache.
> chore: add redis client error event listener

- libs/adsp-service-sdk/src/access/tokenProvider.spec.ts
- libs/adsp-service-sdk/src/access/tokenProvider.ts
- libs/adsp-service-sdk/src/configuration/configurationHandler.spec.ts
Also adding token URL override via environment variable.
> chore(adsp-service-sdk): add token retry

- libs/adsp-feedback/src/main.spec.tsx
- libs/adsp-feedback/src/main.ts
Export is part of the interface and needs to stay compatible for consuming apps.
> fix(adsp-feedback): changing module export back to instance

- README.md
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/metrics.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/overview.tsx
- apps/tenant-management-webapp/src/app/store/comment/action.ts
- apps/tenant-management-webapp/src/app/store/comment/model.ts
- apps/tenant-management-webapp/src/app/store/comment/reducers.ts
- apps/tenant-management-webapp/src/app/store/comment/sagas.ts
- apps/tenant-management-webapp/src/app/store/common/index.ts
- apps/tenant-management-webapp/src/app/store/common/sagas.ts
- apps/tenant-management-webapp/src/app/store/event/sagas.ts
- apps/tenant-management-webapp/src/app/store/file/sagas.ts
- apps/tenant-management-webapp/src/app/store/notification/sagas.ts
- apps/tenant-management-webapp/src/app/store/pdf/api.tsx
- apps/tenant-management-webapp/src/app/store/pdf/sagas.ts
- apps/tenant-management-webapp/src/app/store/status/api.ts
- apps/tenant-management-webapp/src/app/store/status/models.ts
- apps/tenant-management-webapp/src/app/store/status/saga.spec.ts
- apps/tenant-management-webapp/src/app/store/status/sagas.ts
- docs/important-notes.md
- docs/services/directory-service.md
Also adding stats for comment service.
> chore(tenant-management-webapp): refactoring metrics to common saga

- apps/tenant-management-webapp/src/app/store/common/sagas.ts
- apps/tenant-management-webapp/src/app/store/event/sagas.ts
Also retrieving daily interval for events for the per day average stat.
> fix(tenant-management-webapp): updating range to use ISO week

- apps/form-service/src/form/router/form.spec.ts
- apps/form-service/src/form/router/form.swagger.yml
- apps/form-service/src/form/router/form.ts
- apps/form-service/src/mongo/schema.ts
Adding endpoint for getting all submissions. This will be generally for getting submission of a particular definition.
> feat(form-service): add submissions endpoint

- apps/export-service/src/export/events.ts
- apps/export-service/src/export/job/export.spec.ts
- apps/export-service/src/export/job/export.ts
- apps/export-service/src/export/router/export.swagger.yml
- apps/export-service/src/export/router/export.ts
- apps/form-service/src/form/router/form.ts
Also adding error to export failed event.
> fix(form-service): permit core export-job access to submissions

- .openshift/managed/content-service.yml
- apps/content-service/src/adsp-strapi/server/controllers/user.ts
- apps/content-service/src/adsp-strapi/server/events.ts
- apps/content-service/src/adsp-strapi/server/notifications.ts
- apps/content-service/src/adsp-strapi/server/policies/apply-request-tenant.ts
- apps/content-service/src/adsp-strapi/server/policies/is-tenant-content-manager.ts
- apps/content-service/src/adsp-strapi/server/policies/is-tenant-user-with-role.ts
- apps/content-service/src/adsp-strapi/server/register.ts
- apps/content-service/src/api/service-release/content-types/service-release/schema.json
- apps/content-service/src/api/service-release/controllers/service-release.ts
- apps/content-service/src/api/service-release/routes/service-release.ts
- apps/content-service/src/api/service-release/services/service-release.ts
- apps/content-service/types/generated/contentTypes.d.ts
Also include a content type as reference.
> feat(content-service): add registration notification

- apps/form-service/src/form/pdf.ts
- apps/pdf-service/src/handlebars.ts
- apps/pdf-service/src/pdf/partials/elements.hbs
- libs/jsonforms-components/src/lib/Controls/AddressLookup/AddressLookUpControlReview.tsx
- libs/jsonforms-components/src/lib/Controls/AddressLookup/AddressViews.tsx
> fix(dob / case / label) - clean up pdf generation

- libs/jsonforms-components/src/lib/Controls/AddressLookup/AddressViews.tsx
- libs/jsonforms-components/src/lib/Controls/AddressLookup/styled-components.tsx
> fix(postal address): Indentation and address line 1

- apps/tenant-management-webapp/src/app/pages/admin/services/feedback/styled-components.ts
> fix(eye button) - move eye action button to middle - feedback page

- apps/form-service/src/form/notifications.ts
> fix(back to draft) - fix link in email

- apps/script-service/packages.lock.json
- libs/adsp-service-net-sdk/Amqp/AmqpEventSubscriberService.cs
- libs/adsp-service-net-sdk/adsp-service-net-sdk.csproj
- libs/adsp-service-net-sdk/packages.lock.json
Headers don't seem to work with version 7.0.0
> fix(adsp-service-net-sdk,script-service): downgrade rabbit client

- libs/jsonforms-components/src/lib/Controls/FileUploader/FileUploaderControl.tsx
> fix(file uploader) - bottom margin

- apps/form-app/src/app/components/DraftForm.tsx
- apps/form-app/src/app/containers/AnonymousForm.tsx
Also remove saving indicator for anonymous form since it is never shown.
> fix(form-app): scroll inner container for anon form

- libs/jsonforms-components/src/lib/Controls/AddressLookup/AddressViews.tsx
- libs/jsonforms-components/src/lib/Controls/AddressLookup/styled-components.tsx
- libs/jsonforms-components/src/lib/Controls/FullName/FullNameControl.tsx
- libs/jsonforms-components/src/lib/Controls/FullName/FullNameInputs.tsx
- libs/jsonforms-components/src/lib/Controls/FullNameDOB/FullNameDobControl.tsx
- libs/jsonforms-components/src/lib/Controls/FullNameDOB/FullNameDobReviewControl.tsx
> fix(AdressLookup,FullName,FullNameDob): word wrap text when it exceeds container

- apps/form-service/src/form/router/form.swagger.yml
- apps/form-service/src/form/types/formSubmission.ts
- apps/form-service/src/mongo/formSubmission.ts
Allow for finding submissions not yet dispositioned.
> feat(form-service): add a dispositioned criteria

- apps/form-admin-app/src/app/containers/FormAdminTenant.tsx
- apps/form-admin-app/src/app/containers/FormDefinition.tsx
- apps/form-admin-app/src/app/containers/FormDefinitions.tsx
- apps/form-admin-app/src/app/containers/FormSubmission.tsx
- apps/form-admin-app/src/app/state/form.slice.ts
- apps/form-service/src/form/router/form.ts
Also adjusting form admin app routing.
> fix(form-service): include tenantId param on definitions request

- apps/form-admin-app/src/app/components/DetailsLayout.tsx
- apps/form-admin-app/src/app/components/Digest.tsx
- apps/form-admin-app/src/app/components/PropertiesContainer.tsx
- apps/form-admin-app/src/app/containers/Form.tsx
- apps/form-admin-app/src/app/containers/FormDefinitions.tsx
- apps/form-admin-app/src/app/containers/FormSubmission.tsx
- apps/form-admin-app/src/app/containers/FormSubmissions.tsx
- apps/form-admin-app/src/app/containers/Forms.tsx
- apps/token-handler/src/token/router/client.ts
Prevent resetting of multiple pages of results.
> feat(form-service): load only when results are empty

- apps/form-app/src/app/components/DraftForm.tsx
- apps/form-app/src/app/components/DraftFormWrapper.tsx
- apps/form-app/src/app/containers/AnonymousForm.tsx
- apps/form-app/src/app/containers/Form.tsx
Required values check should be handled via validation and not by custom code.
> chore(form-app): removing custom required check

- apps/export-service/src/export/configuration/configuration.ts
- apps/export-service/src/export/configuration/index.ts
- apps/export-service/src/export/configuration/schema.spec.ts
- apps/export-service/src/export/configuration/schema.ts
- apps/export-service/src/export/index.ts
- apps/export-service/src/export/router/export.spec.ts
- apps/export-service/src/export/router/export.ts
- apps/export-service/src/main.ts
Configuration to allow additional roles to create export jobs.
> feat(export-service): support optional configuration

- libs/jsonforms-components/src/lib/util/layout.tsx
> fix(review layout width) - reduce to two items

- apps/form-admin-app/src/app/components/ExportModal.tsx
- apps/form-admin-app/src/app/components/SearchLayout.tsx
- apps/form-admin-app/src/app/containers/FormSubmissions.tsx
- apps/form-admin-app/src/app/containers/Forms.tsx
- apps/form-admin-app/src/app/state/form.slice.ts
- apps/form-admin-app/src/app/state/types.ts
- apps/form-app/src/app/app.module.scss
Also commenting out app styles from form app. With UI components now including most styles, the app styles need to be revisited.
> feat(form-admin-app): add export support.

- apps/form-admin-app/src/app/components/SearchFormItemsContainer.tsx
- apps/form-admin-app/src/app/containers/FormSubmissions.tsx
- apps/form-admin-app/src/app/containers/Forms.tsx
- apps/form-admin-app/src/app/state/form.slice.ts
- apps/form-service/src/mongo/form.ts
- apps/form-service/src/mongo/formSubmission.ts
Also include criteria in export request.
> feat(form-admin-app): support data value search

- libs/jsonforms-components/src/lib/Controls/AddressLookup/styled-components.tsx
Need to use design system variables so that component are styled when design system styles are applied.
> fix(jsonforms-components): replace use of non-standard css vars

- libs/jsonforms-components/src/lib/Controls/Inputs/InputTextControl.tsx
> fix(string type) - populate dropdown if we have registered urn

- apps/form-app/src/app/components/ContinueApplication.tsx
- apps/form-app/src/app/components/DraftFormWrapper.tsx
- apps/form-app/src/app/components/ScheduledIntake.tsx
- apps/form-app/src/app/components/SubmittedForm.tsx
- apps/form-app/src/app/containers/AnonymousForm.tsx
- apps/form-app/src/app/containers/FormDefinition.tsx
- apps/form-app/src/app/containers/FormTenant.tsx
- apps/form-app/src/app/state/form.slice.spec.ts
- apps/form-app/src/app/state/form.slice.ts
- apps/form-app/src/main.tsx
- apps/form-app/src/styles.scss
- libs/app-common/src/components/Recaptcha.tsx
Also adjusting routing based on content hierarchy.
> feat(form-app): hide recaptcha badge

- apps/form-admin-app/src/app/containers/Form.tsx
- apps/form-admin-app/src/app/containers/FormDefinitionOverview.tsx
- apps/form-admin-app/src/app/containers/FormDefinitions.tsx
- apps/form-admin-app/src/app/containers/FormSubmission.tsx
- apps/form-admin-app/src/app/containers/FormSubmissions.tsx
- apps/form-admin-app/src/app/containers/Forms.tsx
- apps/form-admin-app/src/app/state/directory.slice.ts
- apps/form-admin-app/src/app/state/form.slice.ts
Also adjusting some date time formats in views.
> chore(form-admin-app): only load tags if never loaded

- apps/directory-service/src/directory/mapper.ts
- apps/directory-service/src/directory/router/resource.swagger.yml
- apps/directory-service/src/mongo/repository.ts
Also encoding tags link href to handle slashes in resource urn.
> fix(directory-service): adjust swagger criteria param definition

- apps/form-app/src/app/components/Landing.tsx
> fix(accessiblity) - add alt

- libs/jsonforms-components/src/lib/Controls/ObjectArray/styled-components.tsx
> fix(required color and size) - adjust to reqular required size and color

- apps/cache-service/src/cache/model/cacheTarget.ts
401 can be transient and a retry might succeed if it was caused by a token validation issue. Unfortunately the cache service can't distinguish that case easily.
> fix(cache-service): use short TTL on 401 upstream response

- apps/form-admin-app/src/app/app.module.scss
- apps/form-admin-app/src/app/containers/FormAdminTenant.tsx
- apps/form-admin-app/src/app/containers/NavigationMenu.tsx
Support responsive layout behaviour for nav menu on limited width.
> feat(form-admin-app): hide side menu nav on small screen size

- apps/configuration-service/src/main.ts
- apps/form-service/src/form/events.spec.ts
- apps/form-service/src/form/events.ts
- apps/form-service/src/form/mapper.ts
- apps/form-service/src/form/model/form.ts
- apps/form-service/src/form/model/formSubmission.ts
- apps/form-service/src/form/roles.ts
- apps/form-service/src/form/router/form.spec.ts
- apps/form-service/src/form/router/form.swagger.yml
- apps/form-service/src/form/router/form.ts
- apps/form-service/src/form/types/fileTypes.ts
- apps/form-service/src/main.ts
Also, registering resource types for forms and submissions.
> feat(form-service): submission delete endpoint

- libs/jsonforms-components/src/lib/Controls/Inputs/InputNumberControl.spec.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/inputTextControl.spec.tsx
- libs/jsonforms-components/src/lib/Controls/ObjectArray/ObjectArray.spec.tsx
- libs/jsonforms-components/src/lib/Controls/ObjectArray/ObjectListControl.tsx
- libs/jsonforms-components/src/lib/Controls/ObjectArray/arrayData/actions.ts
- libs/jsonforms-components/src/lib/Controls/ObjectArray/arrayData/reducer.ts
- libs/jsonforms-components/src/lib/Controls/ObjectArray/styled-components.tsx
- libs/jsonforms-components/src/lib/util/stringUtils.ts
require should now behave according to jsonform specifications
> fix(CS-3897 - Object array validation errors) - add required label

- apps/form-admin-app/src/app/components/DataValueCriteriaItem.tsx
- apps/form-admin-app/src/app/containers/FormDefinitions.tsx
- apps/form-admin-app/src/app/containers/FormSubmissions.tsx
- apps/form-admin-app/src/app/containers/Forms.tsx
- apps/form-admin-app/src/app/containers/TagSearchFilter.tsx
- apps/form-admin-app/src/app/state/form.slice.ts
- apps/form-service/src/main.ts
Also, supporting tag based search of forms and submissions in admin app.
> fix(form-service): submission resource type updated for urn

- .github/workflows/delivery-ci.yml
- .github/workflows/pull-request.yml
- libs/adsp-service-spring-sdk/pom.xml
- libs/adsp-service-spring-sdk/src/main/java/ca/ab/gov/alberta/adsp/sdk/access/AccessJwtGrantedAuthoritiesConverter.java
- libs/adsp-service-spring-sdk/src/main/java/ca/ab/gov/alberta/adsp/sdk/access/AccessSecurityConfiguration.java
- libs/adsp-service-spring-sdk/src/main/java/ca/ab/gov/alberta/adsp/sdk/tenant/RequestedTenantFilter.java
- libs/adsp-service-spring-sdk/src/test/java/ca/ab/gov/alberta/adsp/sdk/tenant/RequestedTenantFilterTests.java
Done quickly, to compile and be able to use from MCOD application. Please review and make sure all is done properly.
> Upgrade to Spring Boot 3.4.2

- libs/jsonforms-components/src/index.ts
- libs/jsonforms-components/src/lib/Controls/FormStepper/BackButton.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperControl.spec.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperControl.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperTester.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/PageStepperControl.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/context/StepperContext.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/context/util.ts
- libs/jsonforms-components/src/lib/Controls/FormStepper/index.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/styled-components.tsx
> fix(pages layout) - can use pages layout in stepper

- apps/configuration-service/src/configuration/router/configuration.spec.ts
- apps/configuration-service/src/configuration/router/configuration.ts
Calling send status and next results in invalid attempt to rewrite response headers.
> fix(configuration-service): use error and next to return 401

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitions.tsx
- apps/tenant-management-webapp/src/app/store/directory/api.ts
- apps/tenant-management-webapp/src/app/store/form/action.ts
- apps/tenant-management-webapp/src/app/store/form/model.ts
- apps/tenant-management-webapp/src/app/store/form/reducers.ts
- apps/tenant-management-webapp/src/app/store/form/sagas.ts
> feat: filtering formDefinitions by Tag CS-3590

- libs/jsonforms-components/src/lib/Controls/Inputs/InputBooleanControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputEnumCheckboxes.spec.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputEnumCheckboxes.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/style-component.ts
- libs/jsonforms-components/src/lib/Controls/ObjectArray/ObjectListControl.tsx
> fix(checkbox form rules) - fix conditionals, fix checkbox enum

- libs/jsonforms-components/src/lib/Controls/Inputs/InputEnumCheckboxes.tsx
> fix(form conditions) - don't need this

- libs/jsonforms-components/package.json
- libs/jsonforms-components/rollup.config.js
BREAKING CHANGE: requires @abgov/react-components version 5
> feat(jsonforms-components): update react-components to version 5

- apps/form-service/src/form/configuration.ts
- apps/form-service/src/form/notifications.ts
- apps/form-service/src/form/types/definition.ts
Exclude the form link from notifications when no form URL is available.
> feat(form-service): permit empty form URL

- libs/jsonforms-components/src/lib/Controls/Inputs/InputMultiLineTextControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputTextControl.tsx
> fix:allow form configurators to have the option to set the width for InputText

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitions.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/formDefinitionItem.tsx
- apps/tenant-management-webapp/src/app/store/directory/api.ts
- apps/tenant-management-webapp/src/app/store/form/selectors.ts
fix sentence casing, Allow upto 50 tags
> fix:blank scrren for certain Tags

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addRemoveResourceTagModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitions.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/formDefinitionItem.tsx
- apps/tenant-management-webapp/src/app/store/directory/api.ts
- apps/tenant-management-webapp/src/app/store/directory/models.ts
- apps/tenant-management-webapp/src/app/store/form/action.ts
- apps/tenant-management-webapp/src/app/store/form/model.ts
- apps/tenant-management-webapp/src/app/store/form/reducers.ts
- apps/tenant-management-webapp/src/app/store/form/sagas.ts
- apps/tenant-management-webapp/src/app/store/form/selectors.ts
restructure form resource tags in Redux
> fix(tenant-management-webapp): form resource tags filtering, paging, no results

- apps/tenant-management-webapp/src/app/store/pdf/defaultTemplates/body.ts
> fix(show title) - just demonstrate how to create a title

- libs/jsonforms-components/src/lib/Controls/FormStepper/PageStepperControl.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/TableOfContents.tsx
> feat(link to the summary page) - added link

- apps/tenant-management-webapp/src/app/pages/admin/services/cache/cache.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/cacheOverview.tsx
> fix(minor fixes) - add beta tag, fix overview spacing

- apps/tenant-management-webapp/src/app/pages/admin/services/cache/addEditCacheTarget.spec.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/addEditCacheTarget.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/cacheTargetItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/targets.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/targetsList.tsx
> feat(cache target) - edit capability

- apps/tenant-management-webapp/src/app/store/file/models.ts
- apps/tenant-management-webapp/src/app/store/file/reducers.ts
- libs/jsonforms-components/src/lib/Controls/FileUploader/FileUploaderControl.spec.tsx
- libs/jsonforms-components/src/lib/Controls/FileUploader/FileUploaderControl.tsx
> fix(drag and drop upload in form) - supports multiple files now

- apps/notification-service/src/notification/model/type.ts
- apps/tenant-management-webapp/src/app/lib/validation/checkInput.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/addEditNotification/addEditNotification.tsx
Allow notification to be sent by sms or dynamic json sms
pattern is based on validsms
> feat(notification by phone) - Allow notification to be sent by sms

- apps/tenant-management-webapp/src/app/components/AppHeader.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/addEditCacheTarget.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/cacheOverview.tsx
> fix(cache service) - spacing fix, remove core from dropdown

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/categorization.ts
CS-4013-Design a representative form to use as the 'default' populated configuration
> feat-CS-4013-Design a representative form to use as the 'default' populated configuration

- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topics/topicTableItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/comment/topics/topicsTable.tsx
> feat(topic id) - is now displayed

- apps/tenant-management-webapp/src/app/pages/public/SignInError.tsx
> feat(New Tenant) - Add more verbage to prevent tenant creation

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendar/calendarModal.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendar/calendarTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/calendar/calendarsView.tsx
> fix(core calendar) - show view details for core

- apps/tenant-management-webapp/src/app/pages/admin/services/notifications/addEditNotification/addEditNotification.tsx
> feat(notifiy contact) - use three radio buttons instead

- apps/tenant-management-webapp/src/app/pages/admin/services/cache/addEditCacheTarget.spec.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/addEditCacheTarget.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/style-components.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/cache/targetList.spec.tsx
- apps/tenant-management-webapp/src/app/store/cache/model.ts
> feat(cacge target) - support invalidation events

- apps/form-service/src/form/pdf.ts
> fix(form pdf) - was broken, now it should work again

- libs/jsonforms-components/src/lib/Controls/FormStepper/context/util.ts
- libs/jsonforms-components/src/lib/common/Ajv.ts
- libs/jsonforms-components/src/lib/util/useSyncAutofillFields.ts
> fix(jsonforms-components): conditional rule not firing on form load and add useDefaults to Ajv

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/categorization.ts
- Implemented Alberta mailing address autocomplete as the default configuration.
> Fear-CS-4013 Design a representative form to use as the 'default' populated configuration

- libs/jsonforms-components/src/lib/Controls/Inputs/InputBaseReviewControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputbaseReviewControl.spec.tsx
- Refactored checkbox rendering logic to ensure correct bullet point display for multiple selections.
- Added handling for cases where no checkboxes are selected or data is undefined.
> Fix-CS-4159 Form stepper pages variant should have checkbox text in review summary as bullet points.

- apps/tenant-management-webapp/src/app/pages/admin/services/file/fileTypes/editFileTypeDefinitionEditor.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/file/styled-components.ts
> fix(file service) - fix save and back overlap

- apps/tenant-management-webapp/src/app/pages/admin/services/calendar/events/eventListFilter.tsx
> fix(load more): now propery shows extra events when load more is clicked

- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/categorization.ts
improve phone and email validation
> fix-cs-4013 Design a representative form to use as the 'default' populated configuration

- apps/tenant-management-webapp/src/app/pages/admin/services/feedback/overview.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/feedback/sites/edit.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/feedback/sites/sitesList.tsx
> fix(feedback tags) - turn off feature for now

- apps/pdf-service/src/handlebars.ts
> fix(file upload pdf) - now shows correctly with 1 file

- apps/tenant-management-webapp/src/app/pages/admin/services/feedback/feedback/feedbackTableItem.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/feedback/feedback/feedbacks.spec.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/feedback/feedback/feedbacks.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/feedback/feedback/feedbacksTable.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/feedback/styled-components.ts
> feat:Add expanded view for feedback CS-4304

- apps/tenant-management-webapp/src/app/pages/admin/services/status/applications/application.tsx
> feat(orphaned notice): add a notice if there is an attached notice

- .openshift/managed/directory-service.yml
- .openshift/managed/export-service.yml
DeploymentConfig is deprecated.
> chore(directory-service): update to use Deployment

- libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperControl.spec.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/context/StepperContext.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/context/reducer.ts
- libs/jsonforms-components/src/lib/Controls/FormStepper/context/util.ts
> fix: update getIncompletePaths and reducers to fix form stepper status and errors CS-4276

- apps/form-app-e2e/src/integration/forms.feature
- apps/form-app-e2e/src/integration/forms/forms.page.ts
- apps/form-app-e2e/src/integration/forms/forms.step.ts
e2e - Automated tests for anonymous form submission
> e2e - Automated tests for anonymous form submission

- apps/configuration-service/src/configuration/repository/types.ts
- apps/configuration-service/src/configuration/router/configuration.ts
- apps/configuration-service/src/mongo/repository.ts
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/addEditFormDefinition.tsx
- apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitions.tsx
- apps/tenant-management-webapp/src/app/store/form/action.ts
- apps/tenant-management-webapp/src/app/store/form/model.ts
- apps/tenant-management-webapp/src/app/store/form/reducers.ts
- apps/tenant-management-webapp/src/app/store/form/sagas.ts
> feat(registered id) - search by registered id

- libs/data-exchange-standard/src/common.v1.schema.json
- libs/jsonforms-components/src/index.ts
- libs/jsonforms-components/src/lib/Controls/Inputs/InputEmailControl.spec.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/InputEmailControl.tsx
- libs/jsonforms-components/src/lib/Controls/Inputs/index.tsx
> feat(form email): add form email control and email schema

- .github/actions/deploy-app/action.yml
- .github/workflows/delivery-ci.yml
- .github/workflows/promote.yml
Also adding rollout of -job deployment in cases where it exists.
> chore: moving deploy steps into composite action

- apps/task-app/src/app/components/QueueList.tsx
- apps/task-app/src/app/components/QueuesHeader.tsx
- apps/task-app/src/app/components/TaskDetailsLayout.tsx
- apps/task-app/src/app/components/TaskHeader.tsx
- apps/task-app/src/app/components/TaskList.tsx
- apps/task-app/src/app/components/TaskListItem.tsx
- apps/task-app/src/app/containers/TaskQueues.tsx
- apps/task-app/src/app/containers/details/FormSubmissionReviewTask.spec.tsx
- apps/task-app/src/app/containers/details/FormSubmissionReviewTask.tsx
- apps/task-app/src/app/containers/details/FormTask.tsx
- apps/task-app/src/app/containers/details/TaskDetailsHost.tsx
- apps/task-app/src/app/containers/details/styled-components.tsx
- apps/task-app/src/app/state/task.slice.ts
Browser back and forward stays on the same queue and tasks should stay unless queue is changed. Also adjusting layouts for better scroll behaviour.
> fix(task-app): removing extraneous clearing of tasks

- apps/form-app/src/app/containers/Forms.tsx
- apps/form-app/src/app/state/form.slice.ts
- libs/jsonforms-components/src/lib/Controls/FormStepper/styled-components.tsx
Also adjusting form app content.
> chore(jsonforms-components): adjusting form layout for stepper summary

- apps/form-service/src/form/mapper.ts
- apps/form-service/src/form/model/form.spec.ts
- apps/form-service/src/form/model/form.ts
Also including description in form definition in mapping of form responses.
> feat(form-service): remove applicant access to archived forms

- apps/form-app/src/app/containers/Forms.tsx
- apps/form-app/src/app/state/form.slice.ts
- apps/task-app/src/app/components/TaskList.tsx
Also adjusting task list column heading alignment.
> feat(form-app): updating users forms page

- apps/form-app/src/app/components/SignInStartApplication.tsx
- apps/form-app/src/app/containers/Form.tsx
- apps/form-app/src/app/containers/FormDefinition.tsx
- apps/form-app/src/app/containers/Forms.tsx
- apps/form-app/src/app/state/form.slice.ts
Also making adjustments to state for browser back/forward navigation.
> fix(form-app): load more block to avoid layout issue

- apps/form-app/src/app/app.tsx
- apps/form-app/src/app/components/Login.tsx
- apps/form-app/src/app/containers/FormTenant.tsx
- libs/jsonforms-components/src/lib/Controls/AddressLookup/styled-components.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/styled-components.tsx
Also adjusting spacing for login action in app header, and adjusting some form review summary styling.
> feat(form-app): changing default tenant path to /forms

- libs/jsonforms-components/src/lib/Controls/FormStepper/TaskList/categoryRow.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/TaskList/sectionHeaderRow.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/TaskList/summaryRow.tsx
- libs/jsonforms-components/src/lib/Controls/FormStepper/styled-components.tsx
> fix(jsonforms-components): fix index page spacing
